// Code generated by protoc-gen-goten-object
// File: ztna/proto/v1alpha/access_point.proto
// DO NOT EDIT!!!

package access_point

// proto imports
import (
	ntt_meta "github.com/cloudwan/edgelq-sdk/common/types/meta"
	iam_organization "github.com/cloudwan/edgelq-sdk/iam/resources/v1alpha/organization"
	iam_project "github.com/cloudwan/edgelq-sdk/iam/resources/v1alpha/project"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
)

// make sure we're using proto imports
var (
	_ = &ntt_meta.Meta{}
	_ = &iam_organization.Organization{}
	_ = &iam_project.Project{}
	_ = &timestamp.Timestamp{}
)

type AccessPointFieldPathBuilder struct{}

func NewAccessPointFieldPathBuilder() AccessPointFieldPathBuilder {
	return AccessPointFieldPathBuilder{}
}
func (AccessPointFieldPathBuilder) Name() AccessPointPathSelectorName {
	return AccessPointPathSelectorName{}
}

type AccessPointPathSelectorName struct{}

func (AccessPointPathSelectorName) FieldPath() *AccessPoint_FieldTerminalPath {
	return &AccessPoint_FieldTerminalPath{selector: AccessPoint_FieldPathSelectorName}
}

func (s AccessPointPathSelectorName) WithValue(value *Name) *AccessPoint_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*AccessPoint_FieldTerminalPathValue)
}

func (s AccessPointPathSelectorName) WithArrayOfValues(values []*Name) *AccessPoint_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*AccessPoint_FieldTerminalPathArrayOfValues)
}
