// Code generated by protoc-gen-goten-resource
// Resource: AccessPoint
// DO NOT EDIT!!!

package access_point

import (
	gotenobject "github.com/cloudwan/goten-sdk/runtime/object"
	gotenresource "github.com/cloudwan/goten-sdk/runtime/resource"
)

// proto imports
import (
	iam_project "github.com/cloudwan/edgelq-sdk/iam/resources/v1alpha/project"
)

// ensure the imports are used
var (
	_ = gotenobject.FieldPath(nil)
	_ = gotenresource.ListQuery(nil)
)

// make sure we're using proto imports
var (
	_ = &iam_project.Project{}
)

var (
	descriptor = &Descriptor{
		typeName: gotenresource.NewTypeName(
			"AccessPoint", "AccessPoints", "ztna.edgelq.com"),
		nameDescriptor: gotenresource.NewNameDescriptor(
			&AccessPoint_FieldTerminalPath{selector: AccessPoint_FieldPathSelectorName},
			"pattern", "accessPointId",
			[]string{"projectId"},
			[]gotenresource.NamePattern{NamePattern_Project}),
	}
)

type Descriptor struct {
	nameDescriptor *gotenresource.NameDescriptor
	typeName       *gotenresource.TypeName
}

func GetDescriptor() *Descriptor {
	return descriptor
}

func (d *Descriptor) NewAccessPoint() *AccessPoint {
	return &AccessPoint{}
}

func (d *Descriptor) NewResource() gotenresource.Resource {
	return d.NewAccessPoint()
}

func (d *Descriptor) NewResourceName() gotenresource.Name {
	return NewNameBuilder().Name()
}

func (d *Descriptor) NewAccessPointName() *Name {
	return NewNameBuilder().Name()
}

func (d *Descriptor) NewGetQuery() gotenresource.GetQuery {
	return &GetQuery{}
}

func (d *Descriptor) NewListQuery() gotenresource.ListQuery {
	return &ListQuery{}
}

func (d *Descriptor) NewSearchQuery() gotenresource.SearchQuery {
	return nil
}

func (d *Descriptor) NewWatchQuery() gotenresource.WatchQuery {
	return &WatchQuery{}
}
func (d *Descriptor) NewAccessPointCursor() *PagerCursor {
	return &PagerCursor{}
}

func (d *Descriptor) NewResourceCursor() gotenresource.Cursor {
	return d.NewAccessPointCursor()
}
func (d *Descriptor) NewAccessPointChange() *AccessPointChange {
	return &AccessPointChange{}
}

func (d *Descriptor) NewResourceChange() gotenresource.ResourceChange {
	return d.NewAccessPointChange()
}

func (d *Descriptor) NewAccessPointQueryResultSnapshot() *QueryResultSnapshot {
	return &QueryResultSnapshot{}
}

func (d *Descriptor) NewQueryResultSnapshot() gotenresource.QueryResultSnapshot {
	return d.NewAccessPointQueryResultSnapshot()
}
func (d *Descriptor) NewAccessPointQueryResultChange() *QueryResultChange {
	return &QueryResultChange{}
}

func (d *Descriptor) NewSearchQueryResultSnapshot() gotenresource.SearchQueryResultSnapshot {
	return nil
}

func (d *Descriptor) NewQueryResultChange() gotenresource.QueryResultChange {
	return d.NewAccessPointQueryResultChange()
}

func (d *Descriptor) NewAccessPointList(size, reserved int) AccessPointList {
	return make(AccessPointList, size, reserved)
}

func (d *Descriptor) NewResourceList(size, reserved int) gotenresource.ResourceList {
	return make(AccessPointList, size, reserved)
}
func (d *Descriptor) NewAccessPointChangeList(size, reserved int) AccessPointChangeList {
	return make(AccessPointChangeList, size, reserved)
}

func (d *Descriptor) NewResourceChangeList(size, reserved int) gotenresource.ResourceChangeList {
	return make(AccessPointChangeList, size, reserved)
}

func (d *Descriptor) NewAccessPointNameList(size, reserved int) AccessPointNameList {
	return make(AccessPointNameList, size, reserved)
}

func (d *Descriptor) NewNameList(size, reserved int) gotenresource.NameList {
	return make(AccessPointNameList, size, reserved)
}

func (d *Descriptor) NewAccessPointReferenceList(size, reserved int) AccessPointReferenceList {
	return make(AccessPointReferenceList, size, reserved)
}

func (d *Descriptor) NewReferenceList(size, reserved int) gotenresource.ReferenceList {
	return make(AccessPointReferenceList, size, reserved)
}
func (d *Descriptor) NewAccessPointParentNameList(size, reserved int) AccessPointParentNameList {
	return make(AccessPointParentNameList, size, reserved)
}

func (d *Descriptor) NewParentNameList(size, reserved int) gotenresource.ParentNameList {
	return make(AccessPointParentNameList, size, reserved)
}
func (d *Descriptor) NewAccessPointParentReferenceList(size, reserved int) AccessPointParentReferenceList {
	return make(AccessPointParentReferenceList, size, reserved)
}

func (d *Descriptor) NewParentReferenceList(size, reserved int) gotenresource.ParentReferenceList {
	return make(AccessPointParentReferenceList, size, reserved)
}

func (d *Descriptor) NewAccessPointMap(reserved int) AccessPointMap {
	return make(AccessPointMap, reserved)
}

func (d *Descriptor) NewResourceMap(reserved int) gotenresource.ResourceMap {
	return make(AccessPointMap, reserved)
}
func (d *Descriptor) NewAccessPointChangeMap(reserved int) AccessPointChangeMap {
	return make(AccessPointChangeMap, reserved)
}

func (d *Descriptor) NewResourceChangeMap(reserved int) gotenresource.ResourceChangeMap {
	return make(AccessPointChangeMap, reserved)
}

func (d *Descriptor) GetResourceTypeName() *gotenresource.TypeName {
	return d.typeName
}

func (d *Descriptor) GetNameDescriptor() *gotenresource.NameDescriptor {
	return d.nameDescriptor
}

func (d *Descriptor) ParseFieldPath(raw string) (gotenobject.FieldPath, error) {
	return ParseAccessPoint_FieldPath(raw)
}

func (d *Descriptor) ParseAccessPointName(nameStr string) (*Name, error) {
	return ParseName(nameStr)
}

func (d *Descriptor) ParseResourceName(nameStr string) (gotenresource.Name, error) {
	return ParseName(nameStr)
}
