// Code generated by protoc-gen-goten-object
// File: ztna/proto/v1alpha/access_point.proto
// DO NOT EDIT!!!

package access_point

import (
	"encoding/json"
	"fmt"
	"reflect"
	"strings"
	"time"

	"github.com/iancoleman/strcase"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoregistry"
	"google.golang.org/protobuf/types/known/fieldmaskpb"

	gotenobject "github.com/cloudwan/goten-sdk/runtime/object"
)

// proto imports
import (
	iam_project "github.com/cloudwan/edgelq-sdk/iam/resources/v1alpha/project"
)

// ensure the imports are used
var (
	_ = new(json.Marshaler)
	_ = new(fmt.Stringer)
	_ = reflect.DeepEqual
	_ = strings.Builder{}
	_ = time.Second

	_ = strcase.ToLowerCamel
	_ = codes.NotFound
	_ = status.Status{}
	_ = protojson.UnmarshalOptions{}
	_ = new(proto.Message)
	_ = protoregistry.GlobalTypes
	_ = fieldmaskpb.FieldMask{}

	_ = new(gotenobject.FieldPath)
)

// make sure we're using proto imports
var (
	_ = &iam_project.Project{}
)

// FieldPath provides implementation to handle
// https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/field_mask.proto
type AccessPoint_FieldPath interface {
	gotenobject.FieldPath
	Selector() AccessPoint_FieldPathSelector
	Get(source *AccessPoint) []interface{}
	GetSingle(source *AccessPoint) (interface{}, bool)
	ClearValue(item *AccessPoint)

	// Those methods build corresponding AccessPoint_FieldPathValue
	// (or array of values) and holds passed value. Panics if injected type is incorrect.
	WithIValue(value interface{}) AccessPoint_FieldPathValue
	WithIArrayOfValues(values interface{}) AccessPoint_FieldPathArrayOfValues
	WithIArrayItemValue(value interface{}) AccessPoint_FieldPathArrayItemValue
}

type AccessPoint_FieldPathSelector int32

const (
	AccessPoint_FieldPathSelectorName AccessPoint_FieldPathSelector = 0
)

func (s AccessPoint_FieldPathSelector) String() string {
	switch s {
	case AccessPoint_FieldPathSelectorName:
		return "name"
	default:
		panic(fmt.Sprintf("Invalid selector for AccessPoint: %d", s))
	}
}

func BuildAccessPoint_FieldPath(fp gotenobject.RawFieldPath) (AccessPoint_FieldPath, error) {
	if len(fp) == 0 {
		return nil, status.Error(codes.InvalidArgument, "empty field path for object AccessPoint")
	}
	if len(fp) == 1 {
		switch fp[0] {
		case "name":
			return &AccessPoint_FieldTerminalPath{selector: AccessPoint_FieldPathSelectorName}, nil
		}
	}
	return nil, status.Errorf(codes.InvalidArgument, "unknown field path '%s' for object AccessPoint", fp)
}

func ParseAccessPoint_FieldPath(rawField string) (AccessPoint_FieldPath, error) {
	fp, err := gotenobject.ParseRawFieldPath(rawField)
	if err != nil {
		return nil, err
	}
	return BuildAccessPoint_FieldPath(fp)
}

func MustParseAccessPoint_FieldPath(rawField string) AccessPoint_FieldPath {
	fp, err := ParseAccessPoint_FieldPath(rawField)
	if err != nil {
		panic(err)
	}
	return fp
}

type AccessPoint_FieldTerminalPath struct {
	selector AccessPoint_FieldPathSelector
}

var _ AccessPoint_FieldPath = (*AccessPoint_FieldTerminalPath)(nil)

func (fp *AccessPoint_FieldTerminalPath) Selector() AccessPoint_FieldPathSelector {
	return fp.selector
}

// String returns path representation in proto convention
func (fp *AccessPoint_FieldTerminalPath) String() string {
	return fp.selector.String()
}

// JSONString returns path representation is JSON convention
func (fp *AccessPoint_FieldTerminalPath) JSONString() string {
	return strcase.ToLowerCamel(fp.String())
}

// Get returns all values pointed by specific field from source AccessPoint
func (fp *AccessPoint_FieldTerminalPath) Get(source *AccessPoint) (values []interface{}) {
	if source != nil {
		switch fp.selector {
		case AccessPoint_FieldPathSelectorName:
			if source.Name != nil {
				values = append(values, source.Name)
			}
		default:
			panic(fmt.Sprintf("Invalid selector for AccessPoint: %d", fp.selector))
		}
	}
	return
}

func (fp *AccessPoint_FieldTerminalPath) GetRaw(source proto.Message) []interface{} {
	return fp.Get(source.(*AccessPoint))
}

// GetSingle returns value pointed by specific field of from source AccessPoint
func (fp *AccessPoint_FieldTerminalPath) GetSingle(source *AccessPoint) (interface{}, bool) {
	switch fp.selector {
	case AccessPoint_FieldPathSelectorName:
		res := source.GetName()
		return res, res != nil
	default:
		panic(fmt.Sprintf("Invalid selector for AccessPoint: %d", fp.selector))
	}
}

func (fp *AccessPoint_FieldTerminalPath) GetSingleRaw(source proto.Message) (interface{}, bool) {
	return fp.GetSingle(source.(*AccessPoint))
}

// GetDefault returns a default value of the field type
func (fp *AccessPoint_FieldTerminalPath) GetDefault() interface{} {
	switch fp.selector {
	case AccessPoint_FieldPathSelectorName:
		return (*Name)(nil)
	default:
		panic(fmt.Sprintf("Invalid selector for AccessPoint: %d", fp.selector))
	}
}

func (fp *AccessPoint_FieldTerminalPath) ClearValue(item *AccessPoint) {
	if item != nil {
		switch fp.selector {
		case AccessPoint_FieldPathSelectorName:
			item.Name = nil
		default:
			panic(fmt.Sprintf("Invalid selector for AccessPoint: %d", fp.selector))
		}
	}
}

func (fp *AccessPoint_FieldTerminalPath) ClearValueRaw(item proto.Message) {
	fp.ClearValue(item.(*AccessPoint))
}

// IsLeaf - whether field path is holds simple value
func (fp *AccessPoint_FieldTerminalPath) IsLeaf() bool {
	return fp.selector == AccessPoint_FieldPathSelectorName
}

func (fp *AccessPoint_FieldTerminalPath) SplitIntoTerminalIPaths() []gotenobject.FieldPath {
	return []gotenobject.FieldPath{fp}
}

func (fp *AccessPoint_FieldTerminalPath) WithIValue(value interface{}) AccessPoint_FieldPathValue {
	switch fp.selector {
	case AccessPoint_FieldPathSelectorName:
		return &AccessPoint_FieldTerminalPathValue{AccessPoint_FieldTerminalPath: *fp, value: value.(*Name)}
	default:
		panic(fmt.Sprintf("Invalid selector for AccessPoint: %d", fp.selector))
	}
}

func (fp *AccessPoint_FieldTerminalPath) WithRawIValue(value interface{}) gotenobject.FieldPathValue {
	return fp.WithIValue(value)
}

func (fp *AccessPoint_FieldTerminalPath) WithIArrayOfValues(values interface{}) AccessPoint_FieldPathArrayOfValues {
	fpaov := &AccessPoint_FieldTerminalPathArrayOfValues{AccessPoint_FieldTerminalPath: *fp}
	switch fp.selector {
	case AccessPoint_FieldPathSelectorName:
		return &AccessPoint_FieldTerminalPathArrayOfValues{AccessPoint_FieldTerminalPath: *fp, values: values.([]*Name)}
	default:
		panic(fmt.Sprintf("Invalid selector for AccessPoint: %d", fp.selector))
	}
	return fpaov
}

func (fp *AccessPoint_FieldTerminalPath) WithRawIArrayOfValues(values interface{}) gotenobject.FieldPathArrayOfValues {
	return fp.WithIArrayOfValues(values)
}

func (fp *AccessPoint_FieldTerminalPath) WithIArrayItemValue(value interface{}) AccessPoint_FieldPathArrayItemValue {
	switch fp.selector {
	default:
		panic(fmt.Sprintf("Invalid selector for AccessPoint: %d", fp.selector))
	}
}

func (fp *AccessPoint_FieldTerminalPath) WithRawIArrayItemValue(value interface{}) gotenobject.FieldPathArrayItemValue {
	return fp.WithIArrayItemValue(value)
}

// AccessPoint_FieldPathValue allows storing values for AccessPoint fields according to their type
type AccessPoint_FieldPathValue interface {
	AccessPoint_FieldPath
	gotenobject.FieldPathValue
	SetTo(target **AccessPoint)
	CompareWith(*AccessPoint) (cmp int, comparable bool)
}

func ParseAccessPoint_FieldPathValue(pathStr, valueStr string) (AccessPoint_FieldPathValue, error) {
	fp, err := ParseAccessPoint_FieldPath(pathStr)
	if err != nil {
		return nil, err
	}
	fpv, err := gotenobject.ParseFieldPathValue(fp, valueStr)
	if err != nil {
		return nil, status.Errorf(codes.InvalidArgument, "error parsing AccessPoint field path value from %s: %v", valueStr, err)
	}
	return fpv.(AccessPoint_FieldPathValue), nil
}

func MustParseAccessPoint_FieldPathValue(pathStr, valueStr string) AccessPoint_FieldPathValue {
	fpv, err := ParseAccessPoint_FieldPathValue(pathStr, valueStr)
	if err != nil {
		panic(err)
	}
	return fpv
}

type AccessPoint_FieldTerminalPathValue struct {
	AccessPoint_FieldTerminalPath
	value interface{}
}

var _ AccessPoint_FieldPathValue = (*AccessPoint_FieldTerminalPathValue)(nil)

// GetRawValue returns raw value stored under selected path for 'AccessPoint' as interface{}
func (fpv *AccessPoint_FieldTerminalPathValue) GetRawValue() interface{} {
	return fpv.value
}
func (fpv *AccessPoint_FieldTerminalPathValue) AsNameValue() (*Name, bool) {
	res, ok := fpv.value.(*Name)
	return res, ok
}

// SetTo stores value for selected field for object AccessPoint
func (fpv *AccessPoint_FieldTerminalPathValue) SetTo(target **AccessPoint) {
	if *target == nil {
		*target = new(AccessPoint)
	}
	switch fpv.selector {
	case AccessPoint_FieldPathSelectorName:
		(*target).Name = fpv.value.(*Name)
	default:
		panic(fmt.Sprintf("Invalid selector for AccessPoint: %d", fpv.selector))
	}
}

func (fpv *AccessPoint_FieldTerminalPathValue) SetToRaw(target proto.Message) {
	typedObject := target.(*AccessPoint)
	fpv.SetTo(&typedObject)
}

// CompareWith compares value in the 'AccessPoint_FieldTerminalPathValue' with the value under path in 'AccessPoint'.
func (fpv *AccessPoint_FieldTerminalPathValue) CompareWith(source *AccessPoint) (int, bool) {
	switch fpv.selector {
	case AccessPoint_FieldPathSelectorName:
		leftValue := fpv.value.(*Name)
		rightValue := source.GetName()
		if leftValue == nil {
			if rightValue != nil {
				return -1, true
			}
			return 0, true
		}
		if rightValue == nil {
			return 1, true
		}
		if leftValue.String() == rightValue.String() {
			return 0, true
		} else if leftValue.String() < rightValue.String() {
			return -1, true
		} else {
			return 1, true
		}
	default:
		panic(fmt.Sprintf("Invalid selector for AccessPoint: %d", fpv.selector))
	}
}

func (fpv *AccessPoint_FieldTerminalPathValue) CompareWithRaw(source proto.Message) (int, bool) {
	return fpv.CompareWith(source.(*AccessPoint))
}

// AccessPoint_FieldPathArrayItemValue allows storing single item in Path-specific values for AccessPoint according to their type
// Present only for array (repeated) types.
type AccessPoint_FieldPathArrayItemValue interface {
	gotenobject.FieldPathArrayItemValue
	AccessPoint_FieldPath
	ContainsValue(*AccessPoint) bool
}

// ParseAccessPoint_FieldPathArrayItemValue parses string and JSON-encoded value to its Value
func ParseAccessPoint_FieldPathArrayItemValue(pathStr, valueStr string) (AccessPoint_FieldPathArrayItemValue, error) {
	fp, err := ParseAccessPoint_FieldPath(pathStr)
	if err != nil {
		return nil, err
	}
	fpaiv, err := gotenobject.ParseFieldPathArrayItemValue(fp, valueStr)
	if err != nil {
		return nil, status.Errorf(codes.InvalidArgument, "error parsing AccessPoint field path array item value from %s: %v", valueStr, err)
	}
	return fpaiv.(AccessPoint_FieldPathArrayItemValue), nil
}

func MustParseAccessPoint_FieldPathArrayItemValue(pathStr, valueStr string) AccessPoint_FieldPathArrayItemValue {
	fpaiv, err := ParseAccessPoint_FieldPathArrayItemValue(pathStr, valueStr)
	if err != nil {
		panic(err)
	}
	return fpaiv
}

type AccessPoint_FieldTerminalPathArrayItemValue struct {
	AccessPoint_FieldTerminalPath
	value interface{}
}

var _ AccessPoint_FieldPathArrayItemValue = (*AccessPoint_FieldTerminalPathArrayItemValue)(nil)

// GetRawValue returns stored element value for array in object AccessPoint as interface{}
func (fpaiv *AccessPoint_FieldTerminalPathArrayItemValue) GetRawItemValue() interface{} {
	return fpaiv.value
}

func (fpaiv *AccessPoint_FieldTerminalPathArrayItemValue) GetSingle(source *AccessPoint) (interface{}, bool) {
	return nil, false
}

func (fpaiv *AccessPoint_FieldTerminalPathArrayItemValue) GetSingleRaw(source proto.Message) (interface{}, bool) {
	return fpaiv.GetSingle(source.(*AccessPoint))
}

// Contains returns a boolean indicating if value that is being held is present in given 'AccessPoint'
func (fpaiv *AccessPoint_FieldTerminalPathArrayItemValue) ContainsValue(source *AccessPoint) bool {
	slice := fpaiv.AccessPoint_FieldTerminalPath.Get(source)
	for _, v := range slice {
		if asProtoMsg, ok := fpaiv.value.(proto.Message); ok {
			if proto.Equal(asProtoMsg, v.(proto.Message)) {
				return true
			}
		} else if reflect.DeepEqual(v, fpaiv.value) {
			return true
		}
	}
	return false
}

// AccessPoint_FieldPathArrayOfValues allows storing slice of values for AccessPoint fields according to their type
type AccessPoint_FieldPathArrayOfValues interface {
	gotenobject.FieldPathArrayOfValues
	AccessPoint_FieldPath
}

func ParseAccessPoint_FieldPathArrayOfValues(pathStr, valuesStr string) (AccessPoint_FieldPathArrayOfValues, error) {
	fp, err := ParseAccessPoint_FieldPath(pathStr)
	if err != nil {
		return nil, err
	}
	fpaov, err := gotenobject.ParseFieldPathArrayOfValues(fp, valuesStr)
	if err != nil {
		return nil, status.Errorf(codes.InvalidArgument, "error parsing AccessPoint field path array of values from %s: %v", valuesStr, err)
	}
	return fpaov.(AccessPoint_FieldPathArrayOfValues), nil
}

func MustParseAccessPoint_FieldPathArrayOfValues(pathStr, valuesStr string) AccessPoint_FieldPathArrayOfValues {
	fpaov, err := ParseAccessPoint_FieldPathArrayOfValues(pathStr, valuesStr)
	if err != nil {
		panic(err)
	}
	return fpaov
}

type AccessPoint_FieldTerminalPathArrayOfValues struct {
	AccessPoint_FieldTerminalPath
	values interface{}
}

var _ AccessPoint_FieldPathArrayOfValues = (*AccessPoint_FieldTerminalPathArrayOfValues)(nil)

func (fpaov *AccessPoint_FieldTerminalPathArrayOfValues) GetRawValues() (values []interface{}) {
	switch fpaov.selector {
	case AccessPoint_FieldPathSelectorName:
		for _, v := range fpaov.values.([]*Name) {
			values = append(values, v)
		}
	}
	return
}
func (fpaov *AccessPoint_FieldTerminalPathArrayOfValues) AsNameArrayOfValues() ([]*Name, bool) {
	res, ok := fpaov.values.([]*Name)
	return res, ok
}
