// Code generated by protoc-gen-goten-resource
// Resource: AccessPoint
// DO NOT EDIT!!!

package access_point

import (
	"context"

	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"

	"github.com/cloudwan/goten-sdk/runtime/api/watch_type"
	gotenobject "github.com/cloudwan/goten-sdk/runtime/object"
	gotenresource "github.com/cloudwan/goten-sdk/runtime/resource"
)

// proto imports
import (
	iam_project "github.com/cloudwan/edgelq-sdk/iam/resources/v1alpha/project"
)

// ensure the imports are used
var (
	_ = new(context.Context)

	_ = codes.Internal
	_ = status.Status{}

	_ = watch_type.WatchType_STATEFUL
	_ = new(gotenobject.FieldPath)
	_ = new(gotenresource.ListQuery)
)

// make sure we're using proto imports
var (
	_ = &iam_project.Project{}
)

type AccessPointAccess interface {
	GetAccessPoint(context.Context, *GetQuery) (*AccessPoint, error)
	BatchGetAccessPoints(context.Context, []*Reference, ...gotenresource.BatchGetOption) error
	QueryAccessPoints(context.Context, *ListQuery) (*QueryResultSnapshot, error)
	WatchAccessPoint(context.Context, *GetQuery, func(*AccessPointChange) error) error
	WatchAccessPoints(context.Context, *WatchQuery, func(*QueryResultChange) error) error
	SaveAccessPoint(context.Context, *AccessPoint, ...gotenresource.SaveOption) error
	DeleteAccessPoint(context.Context, *Reference, ...gotenresource.DeleteOption) error
}

type anyCastAccess struct {
	AccessPointAccess
}

func AsAnyCastAccess(access AccessPointAccess) gotenresource.Access {
	return &anyCastAccess{AccessPointAccess: access}
}

func (a *anyCastAccess) Get(ctx context.Context, q gotenresource.GetQuery) (gotenresource.Resource, error) {
	if asAccessPointQuery, ok := q.(*GetQuery); ok {
		return a.GetAccessPoint(ctx, asAccessPointQuery)
	}
	return nil, status.Errorf(codes.Internal,
		"Unrecognized descriptor, expected AccessPoint, got: %s",
		q.GetResourceDescriptor().GetResourceTypeName().FullyQualifiedTypeName())
}

func (a *anyCastAccess) Query(ctx context.Context, q gotenresource.ListQuery) (gotenresource.QueryResultSnapshot, error) {
	if asAccessPointQuery, ok := q.(*ListQuery); ok {
		return a.QueryAccessPoints(ctx, asAccessPointQuery)
	}
	return nil, status.Errorf(codes.Internal,
		"Unrecognized descriptor, expected AccessPoint, got: %s",
		q.GetResourceDescriptor().GetResourceTypeName().FullyQualifiedTypeName())
}

func (a *anyCastAccess) Search(ctx context.Context, q gotenresource.SearchQuery) (gotenresource.SearchQueryResultSnapshot, error) {
	return nil, status.Errorf(codes.Internal, "Search is not available for AccessPoint")
}

func (a *anyCastAccess) Watch(ctx context.Context, q gotenresource.GetQuery, cb func(ch gotenresource.ResourceChange) error) error {
	if asAccessPointQuery, ok := q.(*GetQuery); ok {
		return a.WatchAccessPoint(ctx, asAccessPointQuery, func(change *AccessPointChange) error {
			return cb(change)
		})
	}
	return status.Errorf(codes.Internal,
		"Unrecognized descriptor, expected AccessPoint, got: %s",
		q.GetResourceDescriptor().GetResourceTypeName().FullyQualifiedTypeName())
}

func (a *anyCastAccess) WatchQuery(ctx context.Context, q gotenresource.WatchQuery, cb func(ch gotenresource.QueryResultChange) error) error {
	if asAccessPointQuery, ok := q.(*WatchQuery); ok {
		return a.WatchAccessPoints(ctx, asAccessPointQuery, func(change *QueryResultChange) error {
			return cb(change)
		})
	}
	return status.Errorf(codes.Internal,
		"Unrecognized descriptor, expected AccessPoint, got: %s",
		q.GetResourceDescriptor().GetResourceTypeName().FullyQualifiedTypeName())
}

func (a *anyCastAccess) Save(ctx context.Context, res gotenresource.Resource, opts ...gotenresource.SaveOption) error {
	if asAccessPointRes, ok := res.(*AccessPoint); ok {
		return a.SaveAccessPoint(ctx, asAccessPointRes, opts...)
	}
	return status.Errorf(codes.Internal,
		"Unrecognized descriptor, expected AccessPoint, got: %s",
		res.GetResourceDescriptor().GetResourceTypeName().FullyQualifiedTypeName())
}

func (a *anyCastAccess) Delete(ctx context.Context, ref gotenresource.Reference, opts ...gotenresource.DeleteOption) error {
	if asAccessPointRef, ok := ref.(*Reference); ok {
		return a.DeleteAccessPoint(ctx, asAccessPointRef, opts...)
	}
	return status.Errorf(codes.Internal,
		"Unrecognized descriptor, expected AccessPoint, got: %s",
		ref.GetResourceDescriptor().GetResourceTypeName().FullyQualifiedTypeName())
}

func (a *anyCastAccess) BatchGet(ctx context.Context, toGet []gotenresource.Reference, opts ...gotenresource.BatchGetOption) error {
	accessPointRefs := make([]*Reference, 0, len(toGet))
	for _, ref := range toGet {
		if asAccessPointRef, ok := ref.(*Reference); !ok {
			return status.Errorf(codes.Internal,
				"Unrecognized descriptor, expected AccessPoint, got: %s",
				ref.GetResourceDescriptor().GetResourceTypeName().FullyQualifiedTypeName())
		} else {
			accessPointRefs = append(accessPointRefs, asAccessPointRef)
		}
	}
	return a.BatchGetAccessPoints(ctx, accessPointRefs, opts...)
}

func (a *anyCastAccess) GetResourceDescriptors() []gotenresource.Descriptor {
	return []gotenresource.Descriptor{
		GetDescriptor(),
	}
}
