// Code generated by protoc-gen-goten-access
// Service: ZTNA
// DO NOT EDIT!!!

package ztna_access

import (
	gotenresource "github.com/cloudwan/goten-sdk/runtime/resource"

	access_point_access "github.com/cloudwan/ztna-sdk/access/v1alpha/access_point"
	port_forwarding_service_access "github.com/cloudwan/ztna-sdk/access/v1alpha/port_forwarding_service"
	ztna_client "github.com/cloudwan/ztna-sdk/client/v1alpha/ztna"
	access_point "github.com/cloudwan/ztna-sdk/resources/v1alpha/access_point"
	port_forwarding_service "github.com/cloudwan/ztna-sdk/resources/v1alpha/port_forwarding_service"
)

type ZTNAApiAccess interface {
	gotenresource.Access

	access_point.AccessPointAccess
	port_forwarding_service.PortForwardingServiceAccess
}

type apiZTNAAccess struct {
	gotenresource.Access

	access_point.AccessPointAccess
	port_forwarding_service.PortForwardingServiceAccess
}

func NewApiAccess(client ztna_client.ZTNAClient) ZTNAApiAccess {

	accessPointAccess := access_point_access.NewApiAccessPointAccess(client)
	portForwardingServiceAccess := port_forwarding_service_access.NewApiPortForwardingServiceAccess(client)

	return &apiZTNAAccess{
		Access: gotenresource.NewCompositeAccess(

			access_point.AsAnyCastAccess(accessPointAccess),
			port_forwarding_service.AsAnyCastAccess(portForwardingServiceAccess),
		),

		AccessPointAccess:           accessPointAccess,
		PortForwardingServiceAccess: portForwardingServiceAccess,
	}
}
