// Code generated by protoc-gen-goten-access
// Resource: PortForwardingService
// DO NOT EDIT!!!

package port_forwarding_service_access

import (
	"context"
	"fmt"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"

	gotenaccess "github.com/cloudwan/goten-sdk/runtime/access"
	"github.com/cloudwan/goten-sdk/runtime/api/watch_type"
	gotenresource "github.com/cloudwan/goten-sdk/runtime/resource"

	port_forwarding_service_client "github.com/cloudwan/ztna-sdk/client/v1alpha/port_forwarding_service"
	port_forwarding_service "github.com/cloudwan/ztna-sdk/resources/v1alpha/port_forwarding_service"
)

var (
	_ = context.Context(nil)
	_ = fmt.GoStringer(nil)

	_ = grpc.ClientConnInterface(nil)
	_ = codes.NotFound
	_ = status.Status{}

	_ = gotenaccess.Watcher(nil)
	_ = watch_type.WatchType_STATEFUL
	_ = gotenresource.ListQuery(nil)
)

type apiPortForwardingServiceAccess struct {
	client port_forwarding_service_client.PortForwardingServiceServiceClient
}

func NewApiPortForwardingServiceAccess(client port_forwarding_service_client.PortForwardingServiceServiceClient) port_forwarding_service.PortForwardingServiceAccess {
	return &apiPortForwardingServiceAccess{client: client}
}

func (a *apiPortForwardingServiceAccess) GetPortForwardingService(ctx context.Context, query *port_forwarding_service.GetQuery) (*port_forwarding_service.PortForwardingService, error) {
	request := &port_forwarding_service_client.GetPortForwardingServiceRequest{
		Name:      query.Reference,
		FieldMask: query.Mask,
	}
	res, err := a.client.GetPortForwardingService(ctx, request)
	if err != nil {
		return nil, err
	}
	query.Reference.Resolve(res)
	return res, nil
}

func (a *apiPortForwardingServiceAccess) BatchGetPortForwardingServices(ctx context.Context, refs []*port_forwarding_service.Reference, opts ...gotenresource.BatchGetOption) error {
	batchGetOpts := gotenresource.MakeBatchGetOptions(opts)
	request := &port_forwarding_service_client.BatchGetPortForwardingServicesRequest{
		Names: refs,
	}
	resp, err := a.client.BatchGetPortForwardingServices(ctx, request)
	if err != nil {
		return err
	}
	resultMap := make(map[port_forwarding_service.Name]*port_forwarding_service.PortForwardingService, len(refs))
	for _, resolvedRes := range resp.GetPortForwardingServices() {
		resultMap[*resolvedRes.GetName()] = resolvedRes
	}
	for _, ref := range refs {
		resolvedRes := resultMap[ref.Name]
		if resolvedRes != nil {
			ref.Resolve(resolvedRes)
		}
	}
	if batchGetOpts.MustResolveAll() && len(resp.GetMissing()) > 0 {
		return status.Errorf(codes.NotFound, "Number of references not found: %d", len(resp.GetMissing()))
	}
	return nil
}

func (a *apiPortForwardingServiceAccess) QueryPortForwardingServices(ctx context.Context, query *port_forwarding_service.ListQuery) (*port_forwarding_service.QueryResultSnapshot, error) {
	request := &port_forwarding_service_client.ListPortForwardingServicesRequest{
		Filter:    query.Filter,
		FieldMask: query.Mask,
	}
	if query.Pager != nil {
		request.PageSize = int32(query.Pager.Limit)
		request.OrderBy = query.Pager.OrderBy
		request.PageToken = query.Pager.Cursor
	}
	resp, err := a.client.ListPortForwardingServices(ctx, request)
	if err != nil {
		return nil, err
	}
	return &port_forwarding_service.QueryResultSnapshot{
		PortForwardingServices: resp.PortForwardingServices,
		NextPageCursor:         resp.NextPageToken,
		PrevPageCursor:         resp.PrevPageToken,
	}, nil
}

func (a *apiPortForwardingServiceAccess) WatchPortForwardingService(ctx context.Context, query *port_forwarding_service.GetQuery, observerCb func(*port_forwarding_service.PortForwardingServiceChange) error) error {
	request := &port_forwarding_service_client.WatchPortForwardingServiceRequest{
		Name:      query.Reference,
		FieldMask: query.Mask,
	}
	changesStream, initErr := a.client.WatchPortForwardingService(ctx, request)
	if initErr != nil {
		return initErr
	}
	for {
		resp, err := changesStream.Recv()
		if err != nil {
			return fmt.Errorf("watch recv error: %w", err)
		}
		change := resp.GetChange()
		if err := observerCb(change); err != nil {
			return err
		}
	}
}

func (a *apiPortForwardingServiceAccess) WatchPortForwardingServices(ctx context.Context, query *port_forwarding_service.WatchQuery, observerCb func(*port_forwarding_service.QueryResultChange) error) error {
	request := &port_forwarding_service_client.WatchPortForwardingServicesRequest{
		Filter:       query.Filter,
		FieldMask:    query.Mask,
		MaxChunkSize: int32(query.ChunkSize),
		Type:         query.WatchType,
		ResumeToken:  query.ResumeToken,
	}
	if query.Pager != nil {
		request.OrderBy = query.Pager.OrderBy
		request.PageSize = int32(query.Pager.Limit)
		request.PageToken = query.Pager.Cursor
	}
	changesStream, initErr := a.client.WatchPortForwardingServices(ctx, request)
	if initErr != nil {
		return initErr
	}
	for {
		respChange, err := changesStream.Recv()
		if err != nil {
			return fmt.Errorf("watch recv error: %w", err)
		}
		changesWithPaging := &port_forwarding_service.QueryResultChange{
			Changes:      respChange.PortForwardingServiceChanges,
			IsCurrent:    respChange.IsCurrent,
			IsHardReset:  respChange.IsHardReset,
			IsSoftReset:  respChange.IsSoftReset,
			ResumeToken:  respChange.ResumeToken,
			SnapshotSize: respChange.SnapshotSize,
		}
		if respChange.PageTokenChange != nil {
			changesWithPaging.PrevPageCursor = respChange.PageTokenChange.PrevPageToken
			changesWithPaging.NextPageCursor = respChange.PageTokenChange.NextPageToken
		}
		if err := observerCb(changesWithPaging); err != nil {
			return err
		}
	}
}

func (a *apiPortForwardingServiceAccess) SavePortForwardingService(ctx context.Context, res *port_forwarding_service.PortForwardingService, opts ...gotenresource.SaveOption) error {
	saveOpts := gotenresource.MakeSaveOptions(opts)
	previousRes := saveOpts.GetPreviousResource()

	if previousRes == nil && !saveOpts.OnlyUpdate() && !saveOpts.OnlyCreate() {
		var err error
		previousRes, err = a.GetPortForwardingService(ctx, &port_forwarding_service.GetQuery{Reference: res.Name.AsReference()})
		if err != nil {
			if statusErr, ok := status.FromError(err); !ok || statusErr.Code() != codes.NotFound {
				return err
			}
		}
	}

	if saveOpts.OnlyUpdate() || previousRes != nil {
		updateRequest := &port_forwarding_service_client.UpdatePortForwardingServiceRequest{
			PortForwardingService: res,
		}
		if updateMask := saveOpts.GetUpdateMask(); updateMask != nil {
			updateRequest.UpdateMask = updateMask.(*port_forwarding_service.PortForwardingService_FieldMask)
		}
		if mask, conditionalState := saveOpts.GetCAS(); mask != nil && conditionalState != nil {
			updateRequest.Cas = &port_forwarding_service_client.UpdatePortForwardingServiceRequest_CAS{
				ConditionalState: conditionalState.(*port_forwarding_service.PortForwardingService),
				FieldMask:        mask.(*port_forwarding_service.PortForwardingService_FieldMask),
			}
		}
		_, err := a.client.UpdatePortForwardingService(ctx, updateRequest)
		if err != nil {
			return err
		}
		return nil
	} else {
		createRequest := &port_forwarding_service_client.CreatePortForwardingServiceRequest{
			PortForwardingService: res,
		}
		_, err := a.client.CreatePortForwardingService(ctx, createRequest)
		if err != nil {
			return err
		}
		return nil
	}
}

func (a *apiPortForwardingServiceAccess) DeletePortForwardingService(ctx context.Context, ref *port_forwarding_service.Reference, opts ...gotenresource.DeleteOption) error {
	request := &port_forwarding_service_client.DeletePortForwardingServiceRequest{
		Name: ref,
	}
	_, err := a.client.DeletePortForwardingService(ctx, request)
	return err
}

func init() {
	gotenaccess.GetRegistry().RegisterApiAccessConstructor(port_forwarding_service.GetDescriptor(), func(cc grpc.ClientConnInterface) gotenresource.Access {
		return port_forwarding_service.AsAnyCastAccess(NewApiPortForwardingServiceAccess(port_forwarding_service_client.NewPortForwardingServiceServiceClient(cc)))
	})
}
