// Code generated by protoc-gen-goten-resource
// Resource: PortForwardingService
// DO NOT EDIT!!!

package port_forwarding_service

import (
	"context"

	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"

	"github.com/cloudwan/goten-sdk/runtime/api/watch_type"
	gotenobject "github.com/cloudwan/goten-sdk/runtime/object"
	gotenresource "github.com/cloudwan/goten-sdk/runtime/resource"
)

// proto imports
import (
	ntt_meta "github.com/cloudwan/edgelq-sdk/common/types/meta"
	iam_project "github.com/cloudwan/edgelq-sdk/iam/resources/v1alpha/project"
	access_point "github.com/cloudwan/ztna-sdk/resources/v1alpha/access_point"
)

// ensure the imports are used
var (
	_ = new(context.Context)

	_ = codes.Internal
	_ = status.Status{}

	_ = watch_type.WatchType_STATEFUL
	_ = new(gotenobject.FieldPath)
	_ = new(gotenresource.ListQuery)
)

// make sure we're using proto imports
var (
	_ = &ntt_meta.Meta{}
	_ = &iam_project.Project{}
	_ = &access_point.AccessPoint{}
)

type PortForwardingServiceAccess interface {
	GetPortForwardingService(context.Context, *GetQuery) (*PortForwardingService, error)
	BatchGetPortForwardingServices(context.Context, []*Reference, ...gotenresource.BatchGetOption) error
	QueryPortForwardingServices(context.Context, *ListQuery) (*QueryResultSnapshot, error)
	WatchPortForwardingService(context.Context, *GetQuery, func(*PortForwardingServiceChange) error) error
	WatchPortForwardingServices(context.Context, *WatchQuery, func(*QueryResultChange) error) error
	SavePortForwardingService(context.Context, *PortForwardingService, ...gotenresource.SaveOption) error
	DeletePortForwardingService(context.Context, *Reference, ...gotenresource.DeleteOption) error
}

type anyCastAccess struct {
	PortForwardingServiceAccess
}

func AsAnyCastAccess(access PortForwardingServiceAccess) gotenresource.Access {
	return &anyCastAccess{PortForwardingServiceAccess: access}
}

func (a *anyCastAccess) Get(ctx context.Context, q gotenresource.GetQuery) (gotenresource.Resource, error) {
	if asPortForwardingServiceQuery, ok := q.(*GetQuery); ok {
		return a.GetPortForwardingService(ctx, asPortForwardingServiceQuery)
	}
	return nil, status.Errorf(codes.Internal,
		"Unrecognized descriptor, expected PortForwardingService, got: %s",
		q.GetResourceDescriptor().GetResourceTypeName().FullyQualifiedTypeName())
}

func (a *anyCastAccess) Query(ctx context.Context, q gotenresource.ListQuery) (gotenresource.QueryResultSnapshot, error) {
	if asPortForwardingServiceQuery, ok := q.(*ListQuery); ok {
		return a.QueryPortForwardingServices(ctx, asPortForwardingServiceQuery)
	}
	return nil, status.Errorf(codes.Internal,
		"Unrecognized descriptor, expected PortForwardingService, got: %s",
		q.GetResourceDescriptor().GetResourceTypeName().FullyQualifiedTypeName())
}

func (a *anyCastAccess) Search(ctx context.Context, q gotenresource.SearchQuery) (gotenresource.SearchQueryResultSnapshot, error) {
	return nil, status.Errorf(codes.Internal, "Search is not available for PortForwardingService")
}

func (a *anyCastAccess) Watch(ctx context.Context, q gotenresource.GetQuery, cb func(ch gotenresource.ResourceChange) error) error {
	if asPortForwardingServiceQuery, ok := q.(*GetQuery); ok {
		return a.WatchPortForwardingService(ctx, asPortForwardingServiceQuery, func(change *PortForwardingServiceChange) error {
			return cb(change)
		})
	}
	return status.Errorf(codes.Internal,
		"Unrecognized descriptor, expected PortForwardingService, got: %s",
		q.GetResourceDescriptor().GetResourceTypeName().FullyQualifiedTypeName())
}

func (a *anyCastAccess) WatchQuery(ctx context.Context, q gotenresource.WatchQuery, cb func(ch gotenresource.QueryResultChange) error) error {
	if asPortForwardingServiceQuery, ok := q.(*WatchQuery); ok {
		return a.WatchPortForwardingServices(ctx, asPortForwardingServiceQuery, func(change *QueryResultChange) error {
			return cb(change)
		})
	}
	return status.Errorf(codes.Internal,
		"Unrecognized descriptor, expected PortForwardingService, got: %s",
		q.GetResourceDescriptor().GetResourceTypeName().FullyQualifiedTypeName())
}

func (a *anyCastAccess) Save(ctx context.Context, res gotenresource.Resource, opts ...gotenresource.SaveOption) error {
	if asPortForwardingServiceRes, ok := res.(*PortForwardingService); ok {
		return a.SavePortForwardingService(ctx, asPortForwardingServiceRes, opts...)
	}
	return status.Errorf(codes.Internal,
		"Unrecognized descriptor, expected PortForwardingService, got: %s",
		res.GetResourceDescriptor().GetResourceTypeName().FullyQualifiedTypeName())
}

func (a *anyCastAccess) Delete(ctx context.Context, ref gotenresource.Reference, opts ...gotenresource.DeleteOption) error {
	if asPortForwardingServiceRef, ok := ref.(*Reference); ok {
		return a.DeletePortForwardingService(ctx, asPortForwardingServiceRef, opts...)
	}
	return status.Errorf(codes.Internal,
		"Unrecognized descriptor, expected PortForwardingService, got: %s",
		ref.GetResourceDescriptor().GetResourceTypeName().FullyQualifiedTypeName())
}

func (a *anyCastAccess) BatchGet(ctx context.Context, toGet []gotenresource.Reference, opts ...gotenresource.BatchGetOption) error {
	portForwardingServiceRefs := make([]*Reference, 0, len(toGet))
	for _, ref := range toGet {
		if asPortForwardingServiceRef, ok := ref.(*Reference); !ok {
			return status.Errorf(codes.Internal,
				"Unrecognized descriptor, expected PortForwardingService, got: %s",
				ref.GetResourceDescriptor().GetResourceTypeName().FullyQualifiedTypeName())
		} else {
			portForwardingServiceRefs = append(portForwardingServiceRefs, asPortForwardingServiceRef)
		}
	}
	return a.BatchGetPortForwardingServices(ctx, portForwardingServiceRefs, opts...)
}

func (a *anyCastAccess) GetResourceDescriptors() []gotenresource.Descriptor {
	return []gotenresource.Descriptor{
		GetDescriptor(),
	}
}
