// Code generated by protoc-gen-goten-object
// File: ztna/proto/v1alpha/port_forwarding_service.proto
// DO NOT EDIT!!!

package port_forwarding_service

// proto imports
import (
	ntt_meta "github.com/cloudwan/edgelq-sdk/common/types/meta"
	iam_organization "github.com/cloudwan/edgelq-sdk/iam/resources/v1alpha/organization"
	iam_project "github.com/cloudwan/edgelq-sdk/iam/resources/v1alpha/project"
	access_point "github.com/cloudwan/ztna-sdk/resources/v1alpha/access_point"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
)

// make sure we're using proto imports
var (
	_ = &ntt_meta.Meta{}
	_ = &iam_organization.Organization{}
	_ = &iam_project.Project{}
	_ = &timestamp.Timestamp{}
	_ = &access_point.AccessPoint{}
)

type PortForwardingServiceFieldPathBuilder struct{}

func NewPortForwardingServiceFieldPathBuilder() PortForwardingServiceFieldPathBuilder {
	return PortForwardingServiceFieldPathBuilder{}
}
func (PortForwardingServiceFieldPathBuilder) Name() PortForwardingServicePathSelectorName {
	return PortForwardingServicePathSelectorName{}
}
func (PortForwardingServiceFieldPathBuilder) DisplayName() PortForwardingServicePathSelectorDisplayName {
	return PortForwardingServicePathSelectorDisplayName{}
}
func (PortForwardingServiceFieldPathBuilder) Metadata() PortForwardingServicePathSelectorMetadata {
	return PortForwardingServicePathSelectorMetadata{}
}
func (PortForwardingServiceFieldPathBuilder) Spec() PortForwardingServicePathSelectorSpec {
	return PortForwardingServicePathSelectorSpec{}
}
func (PortForwardingServiceFieldPathBuilder) Status() PortForwardingServicePathSelectorStatus {
	return PortForwardingServicePathSelectorStatus{}
}

type PortForwardingServicePathSelectorName struct{}

func (PortForwardingServicePathSelectorName) FieldPath() *PortForwardingService_FieldTerminalPath {
	return &PortForwardingService_FieldTerminalPath{selector: PortForwardingService_FieldPathSelectorName}
}

func (s PortForwardingServicePathSelectorName) WithValue(value *Name) *PortForwardingService_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*PortForwardingService_FieldTerminalPathValue)
}

func (s PortForwardingServicePathSelectorName) WithArrayOfValues(values []*Name) *PortForwardingService_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*PortForwardingService_FieldTerminalPathArrayOfValues)
}

type PortForwardingServicePathSelectorDisplayName struct{}

func (PortForwardingServicePathSelectorDisplayName) FieldPath() *PortForwardingService_FieldTerminalPath {
	return &PortForwardingService_FieldTerminalPath{selector: PortForwardingService_FieldPathSelectorDisplayName}
}

func (s PortForwardingServicePathSelectorDisplayName) WithValue(value string) *PortForwardingService_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*PortForwardingService_FieldTerminalPathValue)
}

func (s PortForwardingServicePathSelectorDisplayName) WithArrayOfValues(values []string) *PortForwardingService_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*PortForwardingService_FieldTerminalPathArrayOfValues)
}

type PortForwardingServicePathSelectorMetadata struct{}

func (PortForwardingServicePathSelectorMetadata) FieldPath() *PortForwardingService_FieldTerminalPath {
	return &PortForwardingService_FieldTerminalPath{selector: PortForwardingService_FieldPathSelectorMetadata}
}

func (s PortForwardingServicePathSelectorMetadata) WithValue(value *ntt_meta.Meta) *PortForwardingService_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*PortForwardingService_FieldTerminalPathValue)
}

func (s PortForwardingServicePathSelectorMetadata) WithArrayOfValues(values []*ntt_meta.Meta) *PortForwardingService_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*PortForwardingService_FieldTerminalPathArrayOfValues)
}

func (PortForwardingServicePathSelectorMetadata) WithSubPath(subPath ntt_meta.Meta_FieldPath) *PortForwardingService_FieldSubPath {
	return &PortForwardingService_FieldSubPath{selector: PortForwardingService_FieldPathSelectorMetadata, subPath: subPath}
}

func (s PortForwardingServicePathSelectorMetadata) WithSubValue(subPathValue ntt_meta.Meta_FieldPathValue) *PortForwardingService_FieldSubPathValue {
	return &PortForwardingService_FieldSubPathValue{PortForwardingService_FieldPath: s.WithSubPath(subPathValue), subPathValue: subPathValue}
}

func (s PortForwardingServicePathSelectorMetadata) WithSubArrayOfValues(subPathArrayOfValues ntt_meta.Meta_FieldPathArrayOfValues) *PortForwardingService_FieldSubPathArrayOfValues {
	return &PortForwardingService_FieldSubPathArrayOfValues{PortForwardingService_FieldPath: s.WithSubPath(subPathArrayOfValues), subPathArrayOfValues: subPathArrayOfValues}
}

func (s PortForwardingServicePathSelectorMetadata) WithSubArrayItemValue(subPathArrayItemValue ntt_meta.Meta_FieldPathArrayItemValue) *PortForwardingService_FieldSubPathArrayItemValue {
	return &PortForwardingService_FieldSubPathArrayItemValue{PortForwardingService_FieldPath: s.WithSubPath(subPathArrayItemValue), subPathItemValue: subPathArrayItemValue}
}

func (PortForwardingServicePathSelectorMetadata) CreateTime() PortForwardingServicePathSelectorMetadataCreateTime {
	return PortForwardingServicePathSelectorMetadataCreateTime{}
}

func (PortForwardingServicePathSelectorMetadata) UpdateTime() PortForwardingServicePathSelectorMetadataUpdateTime {
	return PortForwardingServicePathSelectorMetadataUpdateTime{}
}

func (PortForwardingServicePathSelectorMetadata) Uuid() PortForwardingServicePathSelectorMetadataUuid {
	return PortForwardingServicePathSelectorMetadataUuid{}
}

func (PortForwardingServicePathSelectorMetadata) Tags() PortForwardingServicePathSelectorMetadataTags {
	return PortForwardingServicePathSelectorMetadataTags{}
}

func (PortForwardingServicePathSelectorMetadata) Labels() PortForwardingServicePathSelectorMetadataLabels {
	return PortForwardingServicePathSelectorMetadataLabels{}
}

func (PortForwardingServicePathSelectorMetadata) Annotations() PortForwardingServicePathSelectorMetadataAnnotations {
	return PortForwardingServicePathSelectorMetadataAnnotations{}
}

func (PortForwardingServicePathSelectorMetadata) Generation() PortForwardingServicePathSelectorMetadataGeneration {
	return PortForwardingServicePathSelectorMetadataGeneration{}
}

func (PortForwardingServicePathSelectorMetadata) ResourceVersion() PortForwardingServicePathSelectorMetadataResourceVersion {
	return PortForwardingServicePathSelectorMetadataResourceVersion{}
}

func (PortForwardingServicePathSelectorMetadata) OwnerReferences() PortForwardingServicePathSelectorMetadataOwnerReferences {
	return PortForwardingServicePathSelectorMetadataOwnerReferences{}
}

func (PortForwardingServicePathSelectorMetadata) Shards() PortForwardingServicePathSelectorMetadataShards {
	return PortForwardingServicePathSelectorMetadataShards{}
}

func (PortForwardingServicePathSelectorMetadata) Syncing() PortForwardingServicePathSelectorMetadataSyncing {
	return PortForwardingServicePathSelectorMetadataSyncing{}
}

type PortForwardingServicePathSelectorMetadataCreateTime struct{}

func (PortForwardingServicePathSelectorMetadataCreateTime) FieldPath() *PortForwardingService_FieldSubPath {
	return &PortForwardingService_FieldSubPath{
		selector: PortForwardingService_FieldPathSelectorMetadata,
		subPath:  ntt_meta.NewMetaFieldPathBuilder().CreateTime().FieldPath(),
	}
}

func (s PortForwardingServicePathSelectorMetadataCreateTime) WithValue(value *timestamp.Timestamp) *PortForwardingService_FieldSubPathValue {
	return s.FieldPath().WithIValue(value).(*PortForwardingService_FieldSubPathValue)
}

func (s PortForwardingServicePathSelectorMetadataCreateTime) WithArrayOfValues(values []*timestamp.Timestamp) *PortForwardingService_FieldSubPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*PortForwardingService_FieldSubPathArrayOfValues)
}

type PortForwardingServicePathSelectorMetadataUpdateTime struct{}

func (PortForwardingServicePathSelectorMetadataUpdateTime) FieldPath() *PortForwardingService_FieldSubPath {
	return &PortForwardingService_FieldSubPath{
		selector: PortForwardingService_FieldPathSelectorMetadata,
		subPath:  ntt_meta.NewMetaFieldPathBuilder().UpdateTime().FieldPath(),
	}
}

func (s PortForwardingServicePathSelectorMetadataUpdateTime) WithValue(value *timestamp.Timestamp) *PortForwardingService_FieldSubPathValue {
	return s.FieldPath().WithIValue(value).(*PortForwardingService_FieldSubPathValue)
}

func (s PortForwardingServicePathSelectorMetadataUpdateTime) WithArrayOfValues(values []*timestamp.Timestamp) *PortForwardingService_FieldSubPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*PortForwardingService_FieldSubPathArrayOfValues)
}

type PortForwardingServicePathSelectorMetadataUuid struct{}

func (PortForwardingServicePathSelectorMetadataUuid) FieldPath() *PortForwardingService_FieldSubPath {
	return &PortForwardingService_FieldSubPath{
		selector: PortForwardingService_FieldPathSelectorMetadata,
		subPath:  ntt_meta.NewMetaFieldPathBuilder().Uuid().FieldPath(),
	}
}

func (s PortForwardingServicePathSelectorMetadataUuid) WithValue(value string) *PortForwardingService_FieldSubPathValue {
	return s.FieldPath().WithIValue(value).(*PortForwardingService_FieldSubPathValue)
}

func (s PortForwardingServicePathSelectorMetadataUuid) WithArrayOfValues(values []string) *PortForwardingService_FieldSubPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*PortForwardingService_FieldSubPathArrayOfValues)
}

type PortForwardingServicePathSelectorMetadataTags struct{}

func (PortForwardingServicePathSelectorMetadataTags) FieldPath() *PortForwardingService_FieldSubPath {
	return &PortForwardingService_FieldSubPath{
		selector: PortForwardingService_FieldPathSelectorMetadata,
		subPath:  ntt_meta.NewMetaFieldPathBuilder().Tags().FieldPath(),
	}
}

func (s PortForwardingServicePathSelectorMetadataTags) WithValue(value []string) *PortForwardingService_FieldSubPathValue {
	return s.FieldPath().WithIValue(value).(*PortForwardingService_FieldSubPathValue)
}

func (s PortForwardingServicePathSelectorMetadataTags) WithArrayOfValues(values [][]string) *PortForwardingService_FieldSubPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*PortForwardingService_FieldSubPathArrayOfValues)
}

func (s PortForwardingServicePathSelectorMetadataTags) WithItemValue(value string) *PortForwardingService_FieldSubPathArrayItemValue {
	return s.FieldPath().WithIArrayItemValue(value).(*PortForwardingService_FieldSubPathArrayItemValue)
}

type PortForwardingServicePathSelectorMetadataLabels struct{}

func (PortForwardingServicePathSelectorMetadataLabels) FieldPath() *PortForwardingService_FieldSubPath {
	return &PortForwardingService_FieldSubPath{
		selector: PortForwardingService_FieldPathSelectorMetadata,
		subPath:  ntt_meta.NewMetaFieldPathBuilder().Labels().FieldPath(),
	}
}

func (s PortForwardingServicePathSelectorMetadataLabels) WithValue(value map[string]string) *PortForwardingService_FieldSubPathValue {
	return s.FieldPath().WithIValue(value).(*PortForwardingService_FieldSubPathValue)
}

func (s PortForwardingServicePathSelectorMetadataLabels) WithArrayOfValues(values []map[string]string) *PortForwardingService_FieldSubPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*PortForwardingService_FieldSubPathArrayOfValues)
}

func (PortForwardingServicePathSelectorMetadataLabels) WithKey(key string) PortForwardingServiceMapPathSelectorMetadataLabels {
	return PortForwardingServiceMapPathSelectorMetadataLabels{key: key}
}

type PortForwardingServiceMapPathSelectorMetadataLabels struct {
	key string
}

func (s PortForwardingServiceMapPathSelectorMetadataLabels) FieldPath() *PortForwardingService_FieldSubPath {
	return &PortForwardingService_FieldSubPath{
		selector: PortForwardingService_FieldPathSelectorMetadata,
		subPath:  ntt_meta.NewMetaFieldPathBuilder().Labels().WithKey(s.key).FieldPath(),
	}
}

func (s PortForwardingServiceMapPathSelectorMetadataLabels) WithValue(value string) *PortForwardingService_FieldSubPathValue {
	return s.FieldPath().WithIValue(value).(*PortForwardingService_FieldSubPathValue)
}

func (s PortForwardingServiceMapPathSelectorMetadataLabels) WithArrayOfValues(values []string) *PortForwardingService_FieldSubPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*PortForwardingService_FieldSubPathArrayOfValues)
}

type PortForwardingServicePathSelectorMetadataAnnotations struct{}

func (PortForwardingServicePathSelectorMetadataAnnotations) FieldPath() *PortForwardingService_FieldSubPath {
	return &PortForwardingService_FieldSubPath{
		selector: PortForwardingService_FieldPathSelectorMetadata,
		subPath:  ntt_meta.NewMetaFieldPathBuilder().Annotations().FieldPath(),
	}
}

func (s PortForwardingServicePathSelectorMetadataAnnotations) WithValue(value map[string]string) *PortForwardingService_FieldSubPathValue {
	return s.FieldPath().WithIValue(value).(*PortForwardingService_FieldSubPathValue)
}

func (s PortForwardingServicePathSelectorMetadataAnnotations) WithArrayOfValues(values []map[string]string) *PortForwardingService_FieldSubPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*PortForwardingService_FieldSubPathArrayOfValues)
}

func (PortForwardingServicePathSelectorMetadataAnnotations) WithKey(key string) PortForwardingServiceMapPathSelectorMetadataAnnotations {
	return PortForwardingServiceMapPathSelectorMetadataAnnotations{key: key}
}

type PortForwardingServiceMapPathSelectorMetadataAnnotations struct {
	key string
}

func (s PortForwardingServiceMapPathSelectorMetadataAnnotations) FieldPath() *PortForwardingService_FieldSubPath {
	return &PortForwardingService_FieldSubPath{
		selector: PortForwardingService_FieldPathSelectorMetadata,
		subPath:  ntt_meta.NewMetaFieldPathBuilder().Annotations().WithKey(s.key).FieldPath(),
	}
}

func (s PortForwardingServiceMapPathSelectorMetadataAnnotations) WithValue(value string) *PortForwardingService_FieldSubPathValue {
	return s.FieldPath().WithIValue(value).(*PortForwardingService_FieldSubPathValue)
}

func (s PortForwardingServiceMapPathSelectorMetadataAnnotations) WithArrayOfValues(values []string) *PortForwardingService_FieldSubPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*PortForwardingService_FieldSubPathArrayOfValues)
}

type PortForwardingServicePathSelectorMetadataGeneration struct{}

func (PortForwardingServicePathSelectorMetadataGeneration) FieldPath() *PortForwardingService_FieldSubPath {
	return &PortForwardingService_FieldSubPath{
		selector: PortForwardingService_FieldPathSelectorMetadata,
		subPath:  ntt_meta.NewMetaFieldPathBuilder().Generation().FieldPath(),
	}
}

func (s PortForwardingServicePathSelectorMetadataGeneration) WithValue(value int64) *PortForwardingService_FieldSubPathValue {
	return s.FieldPath().WithIValue(value).(*PortForwardingService_FieldSubPathValue)
}

func (s PortForwardingServicePathSelectorMetadataGeneration) WithArrayOfValues(values []int64) *PortForwardingService_FieldSubPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*PortForwardingService_FieldSubPathArrayOfValues)
}

type PortForwardingServicePathSelectorMetadataResourceVersion struct{}

func (PortForwardingServicePathSelectorMetadataResourceVersion) FieldPath() *PortForwardingService_FieldSubPath {
	return &PortForwardingService_FieldSubPath{
		selector: PortForwardingService_FieldPathSelectorMetadata,
		subPath:  ntt_meta.NewMetaFieldPathBuilder().ResourceVersion().FieldPath(),
	}
}

func (s PortForwardingServicePathSelectorMetadataResourceVersion) WithValue(value string) *PortForwardingService_FieldSubPathValue {
	return s.FieldPath().WithIValue(value).(*PortForwardingService_FieldSubPathValue)
}

func (s PortForwardingServicePathSelectorMetadataResourceVersion) WithArrayOfValues(values []string) *PortForwardingService_FieldSubPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*PortForwardingService_FieldSubPathArrayOfValues)
}

type PortForwardingServicePathSelectorMetadataOwnerReferences struct{}

func (PortForwardingServicePathSelectorMetadataOwnerReferences) FieldPath() *PortForwardingService_FieldSubPath {
	return &PortForwardingService_FieldSubPath{
		selector: PortForwardingService_FieldPathSelectorMetadata,
		subPath:  ntt_meta.NewMetaFieldPathBuilder().OwnerReferences().FieldPath(),
	}
}

func (s PortForwardingServicePathSelectorMetadataOwnerReferences) WithValue(value []*ntt_meta.OwnerReference) *PortForwardingService_FieldSubPathValue {
	return s.FieldPath().WithIValue(value).(*PortForwardingService_FieldSubPathValue)
}

func (s PortForwardingServicePathSelectorMetadataOwnerReferences) WithArrayOfValues(values [][]*ntt_meta.OwnerReference) *PortForwardingService_FieldSubPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*PortForwardingService_FieldSubPathArrayOfValues)
}

func (s PortForwardingServicePathSelectorMetadataOwnerReferences) WithItemValue(value *ntt_meta.OwnerReference) *PortForwardingService_FieldSubPathArrayItemValue {
	return s.FieldPath().WithIArrayItemValue(value).(*PortForwardingService_FieldSubPathArrayItemValue)
}

func (PortForwardingServicePathSelectorMetadataOwnerReferences) ApiVersion() PortForwardingServicePathSelectorMetadataOwnerReferencesApiVersion {
	return PortForwardingServicePathSelectorMetadataOwnerReferencesApiVersion{}
}

func (PortForwardingServicePathSelectorMetadataOwnerReferences) Kind() PortForwardingServicePathSelectorMetadataOwnerReferencesKind {
	return PortForwardingServicePathSelectorMetadataOwnerReferencesKind{}
}

func (PortForwardingServicePathSelectorMetadataOwnerReferences) Name() PortForwardingServicePathSelectorMetadataOwnerReferencesName {
	return PortForwardingServicePathSelectorMetadataOwnerReferencesName{}
}

func (PortForwardingServicePathSelectorMetadataOwnerReferences) Uid() PortForwardingServicePathSelectorMetadataOwnerReferencesUid {
	return PortForwardingServicePathSelectorMetadataOwnerReferencesUid{}
}

func (PortForwardingServicePathSelectorMetadataOwnerReferences) Controller() PortForwardingServicePathSelectorMetadataOwnerReferencesController {
	return PortForwardingServicePathSelectorMetadataOwnerReferencesController{}
}

func (PortForwardingServicePathSelectorMetadataOwnerReferences) BlockOwnerDeletion() PortForwardingServicePathSelectorMetadataOwnerReferencesBlockOwnerDeletion {
	return PortForwardingServicePathSelectorMetadataOwnerReferencesBlockOwnerDeletion{}
}

type PortForwardingServicePathSelectorMetadataOwnerReferencesApiVersion struct{}

func (PortForwardingServicePathSelectorMetadataOwnerReferencesApiVersion) FieldPath() *PortForwardingService_FieldSubPath {
	return &PortForwardingService_FieldSubPath{
		selector: PortForwardingService_FieldPathSelectorMetadata,
		subPath:  ntt_meta.NewMetaFieldPathBuilder().OwnerReferences().ApiVersion().FieldPath(),
	}
}

func (s PortForwardingServicePathSelectorMetadataOwnerReferencesApiVersion) WithValue(value string) *PortForwardingService_FieldSubPathValue {
	return s.FieldPath().WithIValue(value).(*PortForwardingService_FieldSubPathValue)
}

func (s PortForwardingServicePathSelectorMetadataOwnerReferencesApiVersion) WithArrayOfValues(values []string) *PortForwardingService_FieldSubPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*PortForwardingService_FieldSubPathArrayOfValues)
}

type PortForwardingServicePathSelectorMetadataOwnerReferencesKind struct{}

func (PortForwardingServicePathSelectorMetadataOwnerReferencesKind) FieldPath() *PortForwardingService_FieldSubPath {
	return &PortForwardingService_FieldSubPath{
		selector: PortForwardingService_FieldPathSelectorMetadata,
		subPath:  ntt_meta.NewMetaFieldPathBuilder().OwnerReferences().Kind().FieldPath(),
	}
}

func (s PortForwardingServicePathSelectorMetadataOwnerReferencesKind) WithValue(value string) *PortForwardingService_FieldSubPathValue {
	return s.FieldPath().WithIValue(value).(*PortForwardingService_FieldSubPathValue)
}

func (s PortForwardingServicePathSelectorMetadataOwnerReferencesKind) WithArrayOfValues(values []string) *PortForwardingService_FieldSubPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*PortForwardingService_FieldSubPathArrayOfValues)
}

type PortForwardingServicePathSelectorMetadataOwnerReferencesName struct{}

func (PortForwardingServicePathSelectorMetadataOwnerReferencesName) FieldPath() *PortForwardingService_FieldSubPath {
	return &PortForwardingService_FieldSubPath{
		selector: PortForwardingService_FieldPathSelectorMetadata,
		subPath:  ntt_meta.NewMetaFieldPathBuilder().OwnerReferences().Name().FieldPath(),
	}
}

func (s PortForwardingServicePathSelectorMetadataOwnerReferencesName) WithValue(value string) *PortForwardingService_FieldSubPathValue {
	return s.FieldPath().WithIValue(value).(*PortForwardingService_FieldSubPathValue)
}

func (s PortForwardingServicePathSelectorMetadataOwnerReferencesName) WithArrayOfValues(values []string) *PortForwardingService_FieldSubPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*PortForwardingService_FieldSubPathArrayOfValues)
}

type PortForwardingServicePathSelectorMetadataOwnerReferencesUid struct{}

func (PortForwardingServicePathSelectorMetadataOwnerReferencesUid) FieldPath() *PortForwardingService_FieldSubPath {
	return &PortForwardingService_FieldSubPath{
		selector: PortForwardingService_FieldPathSelectorMetadata,
		subPath:  ntt_meta.NewMetaFieldPathBuilder().OwnerReferences().Uid().FieldPath(),
	}
}

func (s PortForwardingServicePathSelectorMetadataOwnerReferencesUid) WithValue(value string) *PortForwardingService_FieldSubPathValue {
	return s.FieldPath().WithIValue(value).(*PortForwardingService_FieldSubPathValue)
}

func (s PortForwardingServicePathSelectorMetadataOwnerReferencesUid) WithArrayOfValues(values []string) *PortForwardingService_FieldSubPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*PortForwardingService_FieldSubPathArrayOfValues)
}

type PortForwardingServicePathSelectorMetadataOwnerReferencesController struct{}

func (PortForwardingServicePathSelectorMetadataOwnerReferencesController) FieldPath() *PortForwardingService_FieldSubPath {
	return &PortForwardingService_FieldSubPath{
		selector: PortForwardingService_FieldPathSelectorMetadata,
		subPath:  ntt_meta.NewMetaFieldPathBuilder().OwnerReferences().Controller().FieldPath(),
	}
}

func (s PortForwardingServicePathSelectorMetadataOwnerReferencesController) WithValue(value bool) *PortForwardingService_FieldSubPathValue {
	return s.FieldPath().WithIValue(value).(*PortForwardingService_FieldSubPathValue)
}

func (s PortForwardingServicePathSelectorMetadataOwnerReferencesController) WithArrayOfValues(values []bool) *PortForwardingService_FieldSubPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*PortForwardingService_FieldSubPathArrayOfValues)
}

type PortForwardingServicePathSelectorMetadataOwnerReferencesBlockOwnerDeletion struct{}

func (PortForwardingServicePathSelectorMetadataOwnerReferencesBlockOwnerDeletion) FieldPath() *PortForwardingService_FieldSubPath {
	return &PortForwardingService_FieldSubPath{
		selector: PortForwardingService_FieldPathSelectorMetadata,
		subPath:  ntt_meta.NewMetaFieldPathBuilder().OwnerReferences().BlockOwnerDeletion().FieldPath(),
	}
}

func (s PortForwardingServicePathSelectorMetadataOwnerReferencesBlockOwnerDeletion) WithValue(value bool) *PortForwardingService_FieldSubPathValue {
	return s.FieldPath().WithIValue(value).(*PortForwardingService_FieldSubPathValue)
}

func (s PortForwardingServicePathSelectorMetadataOwnerReferencesBlockOwnerDeletion) WithArrayOfValues(values []bool) *PortForwardingService_FieldSubPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*PortForwardingService_FieldSubPathArrayOfValues)
}

type PortForwardingServicePathSelectorMetadataShards struct{}

func (PortForwardingServicePathSelectorMetadataShards) FieldPath() *PortForwardingService_FieldSubPath {
	return &PortForwardingService_FieldSubPath{
		selector: PortForwardingService_FieldPathSelectorMetadata,
		subPath:  ntt_meta.NewMetaFieldPathBuilder().Shards().FieldPath(),
	}
}

func (s PortForwardingServicePathSelectorMetadataShards) WithValue(value map[string]int64) *PortForwardingService_FieldSubPathValue {
	return s.FieldPath().WithIValue(value).(*PortForwardingService_FieldSubPathValue)
}

func (s PortForwardingServicePathSelectorMetadataShards) WithArrayOfValues(values []map[string]int64) *PortForwardingService_FieldSubPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*PortForwardingService_FieldSubPathArrayOfValues)
}

func (PortForwardingServicePathSelectorMetadataShards) WithKey(key string) PortForwardingServiceMapPathSelectorMetadataShards {
	return PortForwardingServiceMapPathSelectorMetadataShards{key: key}
}

type PortForwardingServiceMapPathSelectorMetadataShards struct {
	key string
}

func (s PortForwardingServiceMapPathSelectorMetadataShards) FieldPath() *PortForwardingService_FieldSubPath {
	return &PortForwardingService_FieldSubPath{
		selector: PortForwardingService_FieldPathSelectorMetadata,
		subPath:  ntt_meta.NewMetaFieldPathBuilder().Shards().WithKey(s.key).FieldPath(),
	}
}

func (s PortForwardingServiceMapPathSelectorMetadataShards) WithValue(value int64) *PortForwardingService_FieldSubPathValue {
	return s.FieldPath().WithIValue(value).(*PortForwardingService_FieldSubPathValue)
}

func (s PortForwardingServiceMapPathSelectorMetadataShards) WithArrayOfValues(values []int64) *PortForwardingService_FieldSubPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*PortForwardingService_FieldSubPathArrayOfValues)
}

type PortForwardingServicePathSelectorMetadataSyncing struct{}

func (PortForwardingServicePathSelectorMetadataSyncing) FieldPath() *PortForwardingService_FieldSubPath {
	return &PortForwardingService_FieldSubPath{
		selector: PortForwardingService_FieldPathSelectorMetadata,
		subPath:  ntt_meta.NewMetaFieldPathBuilder().Syncing().FieldPath(),
	}
}

func (s PortForwardingServicePathSelectorMetadataSyncing) WithValue(value *ntt_meta.SyncingMeta) *PortForwardingService_FieldSubPathValue {
	return s.FieldPath().WithIValue(value).(*PortForwardingService_FieldSubPathValue)
}

func (s PortForwardingServicePathSelectorMetadataSyncing) WithArrayOfValues(values []*ntt_meta.SyncingMeta) *PortForwardingService_FieldSubPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*PortForwardingService_FieldSubPathArrayOfValues)
}

func (PortForwardingServicePathSelectorMetadataSyncing) OwningRegion() PortForwardingServicePathSelectorMetadataSyncingOwningRegion {
	return PortForwardingServicePathSelectorMetadataSyncingOwningRegion{}
}

func (PortForwardingServicePathSelectorMetadataSyncing) Regions() PortForwardingServicePathSelectorMetadataSyncingRegions {
	return PortForwardingServicePathSelectorMetadataSyncingRegions{}
}

type PortForwardingServicePathSelectorMetadataSyncingOwningRegion struct{}

func (PortForwardingServicePathSelectorMetadataSyncingOwningRegion) FieldPath() *PortForwardingService_FieldSubPath {
	return &PortForwardingService_FieldSubPath{
		selector: PortForwardingService_FieldPathSelectorMetadata,
		subPath:  ntt_meta.NewMetaFieldPathBuilder().Syncing().OwningRegion().FieldPath(),
	}
}

func (s PortForwardingServicePathSelectorMetadataSyncingOwningRegion) WithValue(value string) *PortForwardingService_FieldSubPathValue {
	return s.FieldPath().WithIValue(value).(*PortForwardingService_FieldSubPathValue)
}

func (s PortForwardingServicePathSelectorMetadataSyncingOwningRegion) WithArrayOfValues(values []string) *PortForwardingService_FieldSubPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*PortForwardingService_FieldSubPathArrayOfValues)
}

type PortForwardingServicePathSelectorMetadataSyncingRegions struct{}

func (PortForwardingServicePathSelectorMetadataSyncingRegions) FieldPath() *PortForwardingService_FieldSubPath {
	return &PortForwardingService_FieldSubPath{
		selector: PortForwardingService_FieldPathSelectorMetadata,
		subPath:  ntt_meta.NewMetaFieldPathBuilder().Syncing().Regions().FieldPath(),
	}
}

func (s PortForwardingServicePathSelectorMetadataSyncingRegions) WithValue(value []string) *PortForwardingService_FieldSubPathValue {
	return s.FieldPath().WithIValue(value).(*PortForwardingService_FieldSubPathValue)
}

func (s PortForwardingServicePathSelectorMetadataSyncingRegions) WithArrayOfValues(values [][]string) *PortForwardingService_FieldSubPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*PortForwardingService_FieldSubPathArrayOfValues)
}

func (s PortForwardingServicePathSelectorMetadataSyncingRegions) WithItemValue(value string) *PortForwardingService_FieldSubPathArrayItemValue {
	return s.FieldPath().WithIArrayItemValue(value).(*PortForwardingService_FieldSubPathArrayItemValue)
}

type PortForwardingServicePathSelectorSpec struct{}

func (PortForwardingServicePathSelectorSpec) FieldPath() *PortForwardingService_FieldTerminalPath {
	return &PortForwardingService_FieldTerminalPath{selector: PortForwardingService_FieldPathSelectorSpec}
}

func (s PortForwardingServicePathSelectorSpec) WithValue(value *PortForwardingService_Spec) *PortForwardingService_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*PortForwardingService_FieldTerminalPathValue)
}

func (s PortForwardingServicePathSelectorSpec) WithArrayOfValues(values []*PortForwardingService_Spec) *PortForwardingService_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*PortForwardingService_FieldTerminalPathArrayOfValues)
}

func (PortForwardingServicePathSelectorSpec) WithSubPath(subPath PortForwardingServiceSpec_FieldPath) *PortForwardingService_FieldSubPath {
	return &PortForwardingService_FieldSubPath{selector: PortForwardingService_FieldPathSelectorSpec, subPath: subPath}
}

func (s PortForwardingServicePathSelectorSpec) WithSubValue(subPathValue PortForwardingServiceSpec_FieldPathValue) *PortForwardingService_FieldSubPathValue {
	return &PortForwardingService_FieldSubPathValue{PortForwardingService_FieldPath: s.WithSubPath(subPathValue), subPathValue: subPathValue}
}

func (s PortForwardingServicePathSelectorSpec) WithSubArrayOfValues(subPathArrayOfValues PortForwardingServiceSpec_FieldPathArrayOfValues) *PortForwardingService_FieldSubPathArrayOfValues {
	return &PortForwardingService_FieldSubPathArrayOfValues{PortForwardingService_FieldPath: s.WithSubPath(subPathArrayOfValues), subPathArrayOfValues: subPathArrayOfValues}
}

func (s PortForwardingServicePathSelectorSpec) WithSubArrayItemValue(subPathArrayItemValue PortForwardingServiceSpec_FieldPathArrayItemValue) *PortForwardingService_FieldSubPathArrayItemValue {
	return &PortForwardingService_FieldSubPathArrayItemValue{PortForwardingService_FieldPath: s.WithSubPath(subPathArrayItemValue), subPathItemValue: subPathArrayItemValue}
}

func (PortForwardingServicePathSelectorSpec) Addresses() PortForwardingServicePathSelectorSpecAddresses {
	return PortForwardingServicePathSelectorSpecAddresses{}
}

func (PortForwardingServicePathSelectorSpec) ProviderLoadBalancingMode() PortForwardingServicePathSelectorSpecProviderLoadBalancingMode {
	return PortForwardingServicePathSelectorSpecProviderLoadBalancingMode{}
}

func (PortForwardingServicePathSelectorSpec) TargetLoadBalancingMode() PortForwardingServicePathSelectorSpecTargetLoadBalancingMode {
	return PortForwardingServicePathSelectorSpecTargetLoadBalancingMode{}
}

func (PortForwardingServicePathSelectorSpec) Disabled() PortForwardingServicePathSelectorSpecDisabled {
	return PortForwardingServicePathSelectorSpecDisabled{}
}

func (PortForwardingServicePathSelectorSpec) AccessPoints() PortForwardingServicePathSelectorSpecAccessPoints {
	return PortForwardingServicePathSelectorSpecAccessPoints{}
}

type PortForwardingServicePathSelectorSpecAddresses struct{}

func (PortForwardingServicePathSelectorSpecAddresses) FieldPath() *PortForwardingService_FieldSubPath {
	return &PortForwardingService_FieldSubPath{
		selector: PortForwardingService_FieldPathSelectorSpec,
		subPath:  NewPortForwardingServiceSpecFieldPathBuilder().Addresses().FieldPath(),
	}
}

func (s PortForwardingServicePathSelectorSpecAddresses) WithValue(value []string) *PortForwardingService_FieldSubPathValue {
	return s.FieldPath().WithIValue(value).(*PortForwardingService_FieldSubPathValue)
}

func (s PortForwardingServicePathSelectorSpecAddresses) WithArrayOfValues(values [][]string) *PortForwardingService_FieldSubPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*PortForwardingService_FieldSubPathArrayOfValues)
}

func (s PortForwardingServicePathSelectorSpecAddresses) WithItemValue(value string) *PortForwardingService_FieldSubPathArrayItemValue {
	return s.FieldPath().WithIArrayItemValue(value).(*PortForwardingService_FieldSubPathArrayItemValue)
}

type PortForwardingServicePathSelectorSpecProviderLoadBalancingMode struct{}

func (PortForwardingServicePathSelectorSpecProviderLoadBalancingMode) FieldPath() *PortForwardingService_FieldSubPath {
	return &PortForwardingService_FieldSubPath{
		selector: PortForwardingService_FieldPathSelectorSpec,
		subPath:  NewPortForwardingServiceSpecFieldPathBuilder().ProviderLoadBalancingMode().FieldPath(),
	}
}

func (s PortForwardingServicePathSelectorSpecProviderLoadBalancingMode) WithValue(value PortForwardingService_Spec_LoadBalancingMode) *PortForwardingService_FieldSubPathValue {
	return s.FieldPath().WithIValue(value).(*PortForwardingService_FieldSubPathValue)
}

func (s PortForwardingServicePathSelectorSpecProviderLoadBalancingMode) WithArrayOfValues(values []PortForwardingService_Spec_LoadBalancingMode) *PortForwardingService_FieldSubPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*PortForwardingService_FieldSubPathArrayOfValues)
}

type PortForwardingServicePathSelectorSpecTargetLoadBalancingMode struct{}

func (PortForwardingServicePathSelectorSpecTargetLoadBalancingMode) FieldPath() *PortForwardingService_FieldSubPath {
	return &PortForwardingService_FieldSubPath{
		selector: PortForwardingService_FieldPathSelectorSpec,
		subPath:  NewPortForwardingServiceSpecFieldPathBuilder().TargetLoadBalancingMode().FieldPath(),
	}
}

func (s PortForwardingServicePathSelectorSpecTargetLoadBalancingMode) WithValue(value PortForwardingService_Spec_LoadBalancingMode) *PortForwardingService_FieldSubPathValue {
	return s.FieldPath().WithIValue(value).(*PortForwardingService_FieldSubPathValue)
}

func (s PortForwardingServicePathSelectorSpecTargetLoadBalancingMode) WithArrayOfValues(values []PortForwardingService_Spec_LoadBalancingMode) *PortForwardingService_FieldSubPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*PortForwardingService_FieldSubPathArrayOfValues)
}

type PortForwardingServicePathSelectorSpecDisabled struct{}

func (PortForwardingServicePathSelectorSpecDisabled) FieldPath() *PortForwardingService_FieldSubPath {
	return &PortForwardingService_FieldSubPath{
		selector: PortForwardingService_FieldPathSelectorSpec,
		subPath:  NewPortForwardingServiceSpecFieldPathBuilder().Disabled().FieldPath(),
	}
}

func (s PortForwardingServicePathSelectorSpecDisabled) WithValue(value bool) *PortForwardingService_FieldSubPathValue {
	return s.FieldPath().WithIValue(value).(*PortForwardingService_FieldSubPathValue)
}

func (s PortForwardingServicePathSelectorSpecDisabled) WithArrayOfValues(values []bool) *PortForwardingService_FieldSubPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*PortForwardingService_FieldSubPathArrayOfValues)
}

type PortForwardingServicePathSelectorSpecAccessPoints struct{}

func (PortForwardingServicePathSelectorSpecAccessPoints) FieldPath() *PortForwardingService_FieldSubPath {
	return &PortForwardingService_FieldSubPath{
		selector: PortForwardingService_FieldPathSelectorSpec,
		subPath:  NewPortForwardingServiceSpecFieldPathBuilder().AccessPoints().FieldPath(),
	}
}

func (s PortForwardingServicePathSelectorSpecAccessPoints) WithValue(value []*access_point.Name) *PortForwardingService_FieldSubPathValue {
	return s.FieldPath().WithIValue(value).(*PortForwardingService_FieldSubPathValue)
}

func (s PortForwardingServicePathSelectorSpecAccessPoints) WithArrayOfValues(values [][]*access_point.Name) *PortForwardingService_FieldSubPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*PortForwardingService_FieldSubPathArrayOfValues)
}

func (s PortForwardingServicePathSelectorSpecAccessPoints) WithItemValue(value *access_point.Name) *PortForwardingService_FieldSubPathArrayItemValue {
	return s.FieldPath().WithIArrayItemValue(value).(*PortForwardingService_FieldSubPathArrayItemValue)
}

type PortForwardingServicePathSelectorStatus struct{}

func (PortForwardingServicePathSelectorStatus) FieldPath() *PortForwardingService_FieldTerminalPath {
	return &PortForwardingService_FieldTerminalPath{selector: PortForwardingService_FieldPathSelectorStatus}
}

func (s PortForwardingServicePathSelectorStatus) WithValue(value *PortForwardingService_Status) *PortForwardingService_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*PortForwardingService_FieldTerminalPathValue)
}

func (s PortForwardingServicePathSelectorStatus) WithArrayOfValues(values []*PortForwardingService_Status) *PortForwardingService_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*PortForwardingService_FieldTerminalPathArrayOfValues)
}

func (PortForwardingServicePathSelectorStatus) WithSubPath(subPath PortForwardingServiceStatus_FieldPath) *PortForwardingService_FieldSubPath {
	return &PortForwardingService_FieldSubPath{selector: PortForwardingService_FieldPathSelectorStatus, subPath: subPath}
}

func (s PortForwardingServicePathSelectorStatus) WithSubValue(subPathValue PortForwardingServiceStatus_FieldPathValue) *PortForwardingService_FieldSubPathValue {
	return &PortForwardingService_FieldSubPathValue{PortForwardingService_FieldPath: s.WithSubPath(subPathValue), subPathValue: subPathValue}
}

func (s PortForwardingServicePathSelectorStatus) WithSubArrayOfValues(subPathArrayOfValues PortForwardingServiceStatus_FieldPathArrayOfValues) *PortForwardingService_FieldSubPathArrayOfValues {
	return &PortForwardingService_FieldSubPathArrayOfValues{PortForwardingService_FieldPath: s.WithSubPath(subPathArrayOfValues), subPathArrayOfValues: subPathArrayOfValues}
}

func (s PortForwardingServicePathSelectorStatus) WithSubArrayItemValue(subPathArrayItemValue PortForwardingServiceStatus_FieldPathArrayItemValue) *PortForwardingService_FieldSubPathArrayItemValue {
	return &PortForwardingService_FieldSubPathArrayItemValue{PortForwardingService_FieldPath: s.WithSubPath(subPathArrayItemValue), subPathItemValue: subPathArrayItemValue}
}

type PortForwardingServiceSpecFieldPathBuilder struct{}

func NewPortForwardingServiceSpecFieldPathBuilder() PortForwardingServiceSpecFieldPathBuilder {
	return PortForwardingServiceSpecFieldPathBuilder{}
}
func (PortForwardingServiceSpecFieldPathBuilder) Addresses() PortForwardingService_SpecPathSelectorAddresses {
	return PortForwardingService_SpecPathSelectorAddresses{}
}
func (PortForwardingServiceSpecFieldPathBuilder) ProviderLoadBalancingMode() PortForwardingService_SpecPathSelectorProviderLoadBalancingMode {
	return PortForwardingService_SpecPathSelectorProviderLoadBalancingMode{}
}
func (PortForwardingServiceSpecFieldPathBuilder) TargetLoadBalancingMode() PortForwardingService_SpecPathSelectorTargetLoadBalancingMode {
	return PortForwardingService_SpecPathSelectorTargetLoadBalancingMode{}
}
func (PortForwardingServiceSpecFieldPathBuilder) Disabled() PortForwardingService_SpecPathSelectorDisabled {
	return PortForwardingService_SpecPathSelectorDisabled{}
}
func (PortForwardingServiceSpecFieldPathBuilder) AccessPoints() PortForwardingService_SpecPathSelectorAccessPoints {
	return PortForwardingService_SpecPathSelectorAccessPoints{}
}

type PortForwardingService_SpecPathSelectorAddresses struct{}

func (PortForwardingService_SpecPathSelectorAddresses) FieldPath() *PortForwardingServiceSpec_FieldTerminalPath {
	return &PortForwardingServiceSpec_FieldTerminalPath{selector: PortForwardingServiceSpec_FieldPathSelectorAddresses}
}

func (s PortForwardingService_SpecPathSelectorAddresses) WithValue(value []string) *PortForwardingServiceSpec_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*PortForwardingServiceSpec_FieldTerminalPathValue)
}

func (s PortForwardingService_SpecPathSelectorAddresses) WithArrayOfValues(values [][]string) *PortForwardingServiceSpec_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*PortForwardingServiceSpec_FieldTerminalPathArrayOfValues)
}

func (s PortForwardingService_SpecPathSelectorAddresses) WithItemValue(value string) *PortForwardingServiceSpec_FieldTerminalPathArrayItemValue {
	return s.FieldPath().WithIArrayItemValue(value).(*PortForwardingServiceSpec_FieldTerminalPathArrayItemValue)
}

type PortForwardingService_SpecPathSelectorProviderLoadBalancingMode struct{}

func (PortForwardingService_SpecPathSelectorProviderLoadBalancingMode) FieldPath() *PortForwardingServiceSpec_FieldTerminalPath {
	return &PortForwardingServiceSpec_FieldTerminalPath{selector: PortForwardingServiceSpec_FieldPathSelectorProviderLoadBalancingMode}
}

func (s PortForwardingService_SpecPathSelectorProviderLoadBalancingMode) WithValue(value PortForwardingService_Spec_LoadBalancingMode) *PortForwardingServiceSpec_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*PortForwardingServiceSpec_FieldTerminalPathValue)
}

func (s PortForwardingService_SpecPathSelectorProviderLoadBalancingMode) WithArrayOfValues(values []PortForwardingService_Spec_LoadBalancingMode) *PortForwardingServiceSpec_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*PortForwardingServiceSpec_FieldTerminalPathArrayOfValues)
}

type PortForwardingService_SpecPathSelectorTargetLoadBalancingMode struct{}

func (PortForwardingService_SpecPathSelectorTargetLoadBalancingMode) FieldPath() *PortForwardingServiceSpec_FieldTerminalPath {
	return &PortForwardingServiceSpec_FieldTerminalPath{selector: PortForwardingServiceSpec_FieldPathSelectorTargetLoadBalancingMode}
}

func (s PortForwardingService_SpecPathSelectorTargetLoadBalancingMode) WithValue(value PortForwardingService_Spec_LoadBalancingMode) *PortForwardingServiceSpec_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*PortForwardingServiceSpec_FieldTerminalPathValue)
}

func (s PortForwardingService_SpecPathSelectorTargetLoadBalancingMode) WithArrayOfValues(values []PortForwardingService_Spec_LoadBalancingMode) *PortForwardingServiceSpec_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*PortForwardingServiceSpec_FieldTerminalPathArrayOfValues)
}

type PortForwardingService_SpecPathSelectorDisabled struct{}

func (PortForwardingService_SpecPathSelectorDisabled) FieldPath() *PortForwardingServiceSpec_FieldTerminalPath {
	return &PortForwardingServiceSpec_FieldTerminalPath{selector: PortForwardingServiceSpec_FieldPathSelectorDisabled}
}

func (s PortForwardingService_SpecPathSelectorDisabled) WithValue(value bool) *PortForwardingServiceSpec_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*PortForwardingServiceSpec_FieldTerminalPathValue)
}

func (s PortForwardingService_SpecPathSelectorDisabled) WithArrayOfValues(values []bool) *PortForwardingServiceSpec_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*PortForwardingServiceSpec_FieldTerminalPathArrayOfValues)
}

type PortForwardingService_SpecPathSelectorAccessPoints struct{}

func (PortForwardingService_SpecPathSelectorAccessPoints) FieldPath() *PortForwardingServiceSpec_FieldTerminalPath {
	return &PortForwardingServiceSpec_FieldTerminalPath{selector: PortForwardingServiceSpec_FieldPathSelectorAccessPoints}
}

func (s PortForwardingService_SpecPathSelectorAccessPoints) WithValue(value []*access_point.Name) *PortForwardingServiceSpec_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*PortForwardingServiceSpec_FieldTerminalPathValue)
}

func (s PortForwardingService_SpecPathSelectorAccessPoints) WithArrayOfValues(values [][]*access_point.Name) *PortForwardingServiceSpec_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*PortForwardingServiceSpec_FieldTerminalPathArrayOfValues)
}

func (s PortForwardingService_SpecPathSelectorAccessPoints) WithItemValue(value *access_point.Name) *PortForwardingServiceSpec_FieldTerminalPathArrayItemValue {
	return s.FieldPath().WithIArrayItemValue(value).(*PortForwardingServiceSpec_FieldTerminalPathArrayItemValue)
}

type PortForwardingServiceStatusFieldPathBuilder struct{}

func NewPortForwardingServiceStatusFieldPathBuilder() PortForwardingServiceStatusFieldPathBuilder {
	return PortForwardingServiceStatusFieldPathBuilder{}
}
