// Code generated by protoc-gen-goten-object
// File: ztna/proto/v1alpha/access_point_service.proto
// DO NOT EDIT!!!

package access_point_client

// proto imports
import (
	ntt_meta "github.com/cloudwan/edgelq-sdk/common/types/meta"
	iam_organization "github.com/cloudwan/edgelq-sdk/iam/resources/v1alpha/organization"
	iam_project "github.com/cloudwan/edgelq-sdk/iam/resources/v1alpha/project"
	view "github.com/cloudwan/goten-sdk/runtime/api/view"
	watch_type "github.com/cloudwan/goten-sdk/runtime/api/watch_type"
	access_point "github.com/cloudwan/ztna-sdk/resources/v1alpha/access_point"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	field_mask "google.golang.org/genproto/protobuf/field_mask"
)

// make sure we're using proto imports
var (
	_ = &ntt_meta.Meta{}
	_ = &iam_organization.Organization{}
	_ = &iam_project.Project{}
	_ = &empty.Empty{}
	_ = &field_mask.FieldMask{}
	_ = &timestamp.Timestamp{}
	_ = view.View(0)
	_ = watch_type.WatchType(0)
	_ = &access_point.AccessPoint{}
)

type GetAccessPointRequestFieldPathBuilder struct{}

func NewGetAccessPointRequestFieldPathBuilder() GetAccessPointRequestFieldPathBuilder {
	return GetAccessPointRequestFieldPathBuilder{}
}
func (GetAccessPointRequestFieldPathBuilder) Name() GetAccessPointRequestPathSelectorName {
	return GetAccessPointRequestPathSelectorName{}
}
func (GetAccessPointRequestFieldPathBuilder) FieldMask() GetAccessPointRequestPathSelectorFieldMask {
	return GetAccessPointRequestPathSelectorFieldMask{}
}
func (GetAccessPointRequestFieldPathBuilder) View() GetAccessPointRequestPathSelectorView {
	return GetAccessPointRequestPathSelectorView{}
}

type GetAccessPointRequestPathSelectorName struct{}

func (GetAccessPointRequestPathSelectorName) FieldPath() *GetAccessPointRequest_FieldTerminalPath {
	return &GetAccessPointRequest_FieldTerminalPath{selector: GetAccessPointRequest_FieldPathSelectorName}
}

func (s GetAccessPointRequestPathSelectorName) WithValue(value *access_point.Reference) *GetAccessPointRequest_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*GetAccessPointRequest_FieldTerminalPathValue)
}

func (s GetAccessPointRequestPathSelectorName) WithArrayOfValues(values []*access_point.Reference) *GetAccessPointRequest_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*GetAccessPointRequest_FieldTerminalPathArrayOfValues)
}

type GetAccessPointRequestPathSelectorFieldMask struct{}

func (GetAccessPointRequestPathSelectorFieldMask) FieldPath() *GetAccessPointRequest_FieldTerminalPath {
	return &GetAccessPointRequest_FieldTerminalPath{selector: GetAccessPointRequest_FieldPathSelectorFieldMask}
}

func (s GetAccessPointRequestPathSelectorFieldMask) WithValue(value *access_point.AccessPoint_FieldMask) *GetAccessPointRequest_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*GetAccessPointRequest_FieldTerminalPathValue)
}

func (s GetAccessPointRequestPathSelectorFieldMask) WithArrayOfValues(values []*access_point.AccessPoint_FieldMask) *GetAccessPointRequest_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*GetAccessPointRequest_FieldTerminalPathArrayOfValues)
}

type GetAccessPointRequestPathSelectorView struct{}

func (GetAccessPointRequestPathSelectorView) FieldPath() *GetAccessPointRequest_FieldTerminalPath {
	return &GetAccessPointRequest_FieldTerminalPath{selector: GetAccessPointRequest_FieldPathSelectorView}
}

func (s GetAccessPointRequestPathSelectorView) WithValue(value view.View) *GetAccessPointRequest_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*GetAccessPointRequest_FieldTerminalPathValue)
}

func (s GetAccessPointRequestPathSelectorView) WithArrayOfValues(values []view.View) *GetAccessPointRequest_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*GetAccessPointRequest_FieldTerminalPathArrayOfValues)
}

type BatchGetAccessPointsRequestFieldPathBuilder struct{}

func NewBatchGetAccessPointsRequestFieldPathBuilder() BatchGetAccessPointsRequestFieldPathBuilder {
	return BatchGetAccessPointsRequestFieldPathBuilder{}
}
func (BatchGetAccessPointsRequestFieldPathBuilder) Names() BatchGetAccessPointsRequestPathSelectorNames {
	return BatchGetAccessPointsRequestPathSelectorNames{}
}
func (BatchGetAccessPointsRequestFieldPathBuilder) FieldMask() BatchGetAccessPointsRequestPathSelectorFieldMask {
	return BatchGetAccessPointsRequestPathSelectorFieldMask{}
}
func (BatchGetAccessPointsRequestFieldPathBuilder) View() BatchGetAccessPointsRequestPathSelectorView {
	return BatchGetAccessPointsRequestPathSelectorView{}
}

type BatchGetAccessPointsRequestPathSelectorNames struct{}

func (BatchGetAccessPointsRequestPathSelectorNames) FieldPath() *BatchGetAccessPointsRequest_FieldTerminalPath {
	return &BatchGetAccessPointsRequest_FieldTerminalPath{selector: BatchGetAccessPointsRequest_FieldPathSelectorNames}
}

func (s BatchGetAccessPointsRequestPathSelectorNames) WithValue(value []*access_point.Reference) *BatchGetAccessPointsRequest_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*BatchGetAccessPointsRequest_FieldTerminalPathValue)
}

func (s BatchGetAccessPointsRequestPathSelectorNames) WithArrayOfValues(values [][]*access_point.Reference) *BatchGetAccessPointsRequest_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*BatchGetAccessPointsRequest_FieldTerminalPathArrayOfValues)
}

func (s BatchGetAccessPointsRequestPathSelectorNames) WithItemValue(value *access_point.Reference) *BatchGetAccessPointsRequest_FieldTerminalPathArrayItemValue {
	return s.FieldPath().WithIArrayItemValue(value).(*BatchGetAccessPointsRequest_FieldTerminalPathArrayItemValue)
}

type BatchGetAccessPointsRequestPathSelectorFieldMask struct{}

func (BatchGetAccessPointsRequestPathSelectorFieldMask) FieldPath() *BatchGetAccessPointsRequest_FieldTerminalPath {
	return &BatchGetAccessPointsRequest_FieldTerminalPath{selector: BatchGetAccessPointsRequest_FieldPathSelectorFieldMask}
}

func (s BatchGetAccessPointsRequestPathSelectorFieldMask) WithValue(value *access_point.AccessPoint_FieldMask) *BatchGetAccessPointsRequest_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*BatchGetAccessPointsRequest_FieldTerminalPathValue)
}

func (s BatchGetAccessPointsRequestPathSelectorFieldMask) WithArrayOfValues(values []*access_point.AccessPoint_FieldMask) *BatchGetAccessPointsRequest_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*BatchGetAccessPointsRequest_FieldTerminalPathArrayOfValues)
}

type BatchGetAccessPointsRequestPathSelectorView struct{}

func (BatchGetAccessPointsRequestPathSelectorView) FieldPath() *BatchGetAccessPointsRequest_FieldTerminalPath {
	return &BatchGetAccessPointsRequest_FieldTerminalPath{selector: BatchGetAccessPointsRequest_FieldPathSelectorView}
}

func (s BatchGetAccessPointsRequestPathSelectorView) WithValue(value view.View) *BatchGetAccessPointsRequest_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*BatchGetAccessPointsRequest_FieldTerminalPathValue)
}

func (s BatchGetAccessPointsRequestPathSelectorView) WithArrayOfValues(values []view.View) *BatchGetAccessPointsRequest_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*BatchGetAccessPointsRequest_FieldTerminalPathArrayOfValues)
}

type BatchGetAccessPointsResponseFieldPathBuilder struct{}

func NewBatchGetAccessPointsResponseFieldPathBuilder() BatchGetAccessPointsResponseFieldPathBuilder {
	return BatchGetAccessPointsResponseFieldPathBuilder{}
}
func (BatchGetAccessPointsResponseFieldPathBuilder) AccessPoints() BatchGetAccessPointsResponsePathSelectorAccessPoints {
	return BatchGetAccessPointsResponsePathSelectorAccessPoints{}
}
func (BatchGetAccessPointsResponseFieldPathBuilder) Missing() BatchGetAccessPointsResponsePathSelectorMissing {
	return BatchGetAccessPointsResponsePathSelectorMissing{}
}

type BatchGetAccessPointsResponsePathSelectorAccessPoints struct{}

func (BatchGetAccessPointsResponsePathSelectorAccessPoints) FieldPath() *BatchGetAccessPointsResponse_FieldTerminalPath {
	return &BatchGetAccessPointsResponse_FieldTerminalPath{selector: BatchGetAccessPointsResponse_FieldPathSelectorAccessPoints}
}

func (s BatchGetAccessPointsResponsePathSelectorAccessPoints) WithValue(value []*access_point.AccessPoint) *BatchGetAccessPointsResponse_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*BatchGetAccessPointsResponse_FieldTerminalPathValue)
}

func (s BatchGetAccessPointsResponsePathSelectorAccessPoints) WithArrayOfValues(values [][]*access_point.AccessPoint) *BatchGetAccessPointsResponse_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*BatchGetAccessPointsResponse_FieldTerminalPathArrayOfValues)
}

func (s BatchGetAccessPointsResponsePathSelectorAccessPoints) WithItemValue(value *access_point.AccessPoint) *BatchGetAccessPointsResponse_FieldTerminalPathArrayItemValue {
	return s.FieldPath().WithIArrayItemValue(value).(*BatchGetAccessPointsResponse_FieldTerminalPathArrayItemValue)
}
func (BatchGetAccessPointsResponsePathSelectorAccessPoints) WithSubPath(subPath access_point.AccessPoint_FieldPath) *BatchGetAccessPointsResponse_FieldSubPath {
	return &BatchGetAccessPointsResponse_FieldSubPath{selector: BatchGetAccessPointsResponse_FieldPathSelectorAccessPoints, subPath: subPath}
}

func (s BatchGetAccessPointsResponsePathSelectorAccessPoints) WithSubValue(subPathValue access_point.AccessPoint_FieldPathValue) *BatchGetAccessPointsResponse_FieldSubPathValue {
	return &BatchGetAccessPointsResponse_FieldSubPathValue{BatchGetAccessPointsResponse_FieldPath: s.WithSubPath(subPathValue), subPathValue: subPathValue}
}

func (s BatchGetAccessPointsResponsePathSelectorAccessPoints) WithSubArrayOfValues(subPathArrayOfValues access_point.AccessPoint_FieldPathArrayOfValues) *BatchGetAccessPointsResponse_FieldSubPathArrayOfValues {
	return &BatchGetAccessPointsResponse_FieldSubPathArrayOfValues{BatchGetAccessPointsResponse_FieldPath: s.WithSubPath(subPathArrayOfValues), subPathArrayOfValues: subPathArrayOfValues}
}

func (s BatchGetAccessPointsResponsePathSelectorAccessPoints) WithSubArrayItemValue(subPathArrayItemValue access_point.AccessPoint_FieldPathArrayItemValue) *BatchGetAccessPointsResponse_FieldSubPathArrayItemValue {
	return &BatchGetAccessPointsResponse_FieldSubPathArrayItemValue{BatchGetAccessPointsResponse_FieldPath: s.WithSubPath(subPathArrayItemValue), subPathItemValue: subPathArrayItemValue}
}

func (BatchGetAccessPointsResponsePathSelectorAccessPoints) Name() BatchGetAccessPointsResponsePathSelectorAccessPointsName {
	return BatchGetAccessPointsResponsePathSelectorAccessPointsName{}
}

type BatchGetAccessPointsResponsePathSelectorAccessPointsName struct{}

func (BatchGetAccessPointsResponsePathSelectorAccessPointsName) FieldPath() *BatchGetAccessPointsResponse_FieldSubPath {
	return &BatchGetAccessPointsResponse_FieldSubPath{
		selector: BatchGetAccessPointsResponse_FieldPathSelectorAccessPoints,
		subPath:  access_point.NewAccessPointFieldPathBuilder().Name().FieldPath(),
	}
}

func (s BatchGetAccessPointsResponsePathSelectorAccessPointsName) WithValue(value *access_point.Name) *BatchGetAccessPointsResponse_FieldSubPathValue {
	return s.FieldPath().WithIValue(value).(*BatchGetAccessPointsResponse_FieldSubPathValue)
}

func (s BatchGetAccessPointsResponsePathSelectorAccessPointsName) WithArrayOfValues(values []*access_point.Name) *BatchGetAccessPointsResponse_FieldSubPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*BatchGetAccessPointsResponse_FieldSubPathArrayOfValues)
}

type BatchGetAccessPointsResponsePathSelectorMissing struct{}

func (BatchGetAccessPointsResponsePathSelectorMissing) FieldPath() *BatchGetAccessPointsResponse_FieldTerminalPath {
	return &BatchGetAccessPointsResponse_FieldTerminalPath{selector: BatchGetAccessPointsResponse_FieldPathSelectorMissing}
}

func (s BatchGetAccessPointsResponsePathSelectorMissing) WithValue(value []*access_point.Reference) *BatchGetAccessPointsResponse_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*BatchGetAccessPointsResponse_FieldTerminalPathValue)
}

func (s BatchGetAccessPointsResponsePathSelectorMissing) WithArrayOfValues(values [][]*access_point.Reference) *BatchGetAccessPointsResponse_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*BatchGetAccessPointsResponse_FieldTerminalPathArrayOfValues)
}

func (s BatchGetAccessPointsResponsePathSelectorMissing) WithItemValue(value *access_point.Reference) *BatchGetAccessPointsResponse_FieldTerminalPathArrayItemValue {
	return s.FieldPath().WithIArrayItemValue(value).(*BatchGetAccessPointsResponse_FieldTerminalPathArrayItemValue)
}

type ListAccessPointsRequestFieldPathBuilder struct{}

func NewListAccessPointsRequestFieldPathBuilder() ListAccessPointsRequestFieldPathBuilder {
	return ListAccessPointsRequestFieldPathBuilder{}
}
func (ListAccessPointsRequestFieldPathBuilder) Parent() ListAccessPointsRequestPathSelectorParent {
	return ListAccessPointsRequestPathSelectorParent{}
}
func (ListAccessPointsRequestFieldPathBuilder) PageSize() ListAccessPointsRequestPathSelectorPageSize {
	return ListAccessPointsRequestPathSelectorPageSize{}
}
func (ListAccessPointsRequestFieldPathBuilder) PageToken() ListAccessPointsRequestPathSelectorPageToken {
	return ListAccessPointsRequestPathSelectorPageToken{}
}
func (ListAccessPointsRequestFieldPathBuilder) OrderBy() ListAccessPointsRequestPathSelectorOrderBy {
	return ListAccessPointsRequestPathSelectorOrderBy{}
}
func (ListAccessPointsRequestFieldPathBuilder) Filter() ListAccessPointsRequestPathSelectorFilter {
	return ListAccessPointsRequestPathSelectorFilter{}
}
func (ListAccessPointsRequestFieldPathBuilder) FieldMask() ListAccessPointsRequestPathSelectorFieldMask {
	return ListAccessPointsRequestPathSelectorFieldMask{}
}
func (ListAccessPointsRequestFieldPathBuilder) View() ListAccessPointsRequestPathSelectorView {
	return ListAccessPointsRequestPathSelectorView{}
}

type ListAccessPointsRequestPathSelectorParent struct{}

func (ListAccessPointsRequestPathSelectorParent) FieldPath() *ListAccessPointsRequest_FieldTerminalPath {
	return &ListAccessPointsRequest_FieldTerminalPath{selector: ListAccessPointsRequest_FieldPathSelectorParent}
}

func (s ListAccessPointsRequestPathSelectorParent) WithValue(value *access_point.ParentName) *ListAccessPointsRequest_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*ListAccessPointsRequest_FieldTerminalPathValue)
}

func (s ListAccessPointsRequestPathSelectorParent) WithArrayOfValues(values []*access_point.ParentName) *ListAccessPointsRequest_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*ListAccessPointsRequest_FieldTerminalPathArrayOfValues)
}

type ListAccessPointsRequestPathSelectorPageSize struct{}

func (ListAccessPointsRequestPathSelectorPageSize) FieldPath() *ListAccessPointsRequest_FieldTerminalPath {
	return &ListAccessPointsRequest_FieldTerminalPath{selector: ListAccessPointsRequest_FieldPathSelectorPageSize}
}

func (s ListAccessPointsRequestPathSelectorPageSize) WithValue(value int32) *ListAccessPointsRequest_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*ListAccessPointsRequest_FieldTerminalPathValue)
}

func (s ListAccessPointsRequestPathSelectorPageSize) WithArrayOfValues(values []int32) *ListAccessPointsRequest_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*ListAccessPointsRequest_FieldTerminalPathArrayOfValues)
}

type ListAccessPointsRequestPathSelectorPageToken struct{}

func (ListAccessPointsRequestPathSelectorPageToken) FieldPath() *ListAccessPointsRequest_FieldTerminalPath {
	return &ListAccessPointsRequest_FieldTerminalPath{selector: ListAccessPointsRequest_FieldPathSelectorPageToken}
}

func (s ListAccessPointsRequestPathSelectorPageToken) WithValue(value *access_point.PagerCursor) *ListAccessPointsRequest_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*ListAccessPointsRequest_FieldTerminalPathValue)
}

func (s ListAccessPointsRequestPathSelectorPageToken) WithArrayOfValues(values []*access_point.PagerCursor) *ListAccessPointsRequest_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*ListAccessPointsRequest_FieldTerminalPathArrayOfValues)
}

type ListAccessPointsRequestPathSelectorOrderBy struct{}

func (ListAccessPointsRequestPathSelectorOrderBy) FieldPath() *ListAccessPointsRequest_FieldTerminalPath {
	return &ListAccessPointsRequest_FieldTerminalPath{selector: ListAccessPointsRequest_FieldPathSelectorOrderBy}
}

func (s ListAccessPointsRequestPathSelectorOrderBy) WithValue(value *access_point.OrderBy) *ListAccessPointsRequest_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*ListAccessPointsRequest_FieldTerminalPathValue)
}

func (s ListAccessPointsRequestPathSelectorOrderBy) WithArrayOfValues(values []*access_point.OrderBy) *ListAccessPointsRequest_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*ListAccessPointsRequest_FieldTerminalPathArrayOfValues)
}

type ListAccessPointsRequestPathSelectorFilter struct{}

func (ListAccessPointsRequestPathSelectorFilter) FieldPath() *ListAccessPointsRequest_FieldTerminalPath {
	return &ListAccessPointsRequest_FieldTerminalPath{selector: ListAccessPointsRequest_FieldPathSelectorFilter}
}

func (s ListAccessPointsRequestPathSelectorFilter) WithValue(value *access_point.Filter) *ListAccessPointsRequest_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*ListAccessPointsRequest_FieldTerminalPathValue)
}

func (s ListAccessPointsRequestPathSelectorFilter) WithArrayOfValues(values []*access_point.Filter) *ListAccessPointsRequest_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*ListAccessPointsRequest_FieldTerminalPathArrayOfValues)
}

type ListAccessPointsRequestPathSelectorFieldMask struct{}

func (ListAccessPointsRequestPathSelectorFieldMask) FieldPath() *ListAccessPointsRequest_FieldTerminalPath {
	return &ListAccessPointsRequest_FieldTerminalPath{selector: ListAccessPointsRequest_FieldPathSelectorFieldMask}
}

func (s ListAccessPointsRequestPathSelectorFieldMask) WithValue(value *access_point.AccessPoint_FieldMask) *ListAccessPointsRequest_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*ListAccessPointsRequest_FieldTerminalPathValue)
}

func (s ListAccessPointsRequestPathSelectorFieldMask) WithArrayOfValues(values []*access_point.AccessPoint_FieldMask) *ListAccessPointsRequest_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*ListAccessPointsRequest_FieldTerminalPathArrayOfValues)
}

type ListAccessPointsRequestPathSelectorView struct{}

func (ListAccessPointsRequestPathSelectorView) FieldPath() *ListAccessPointsRequest_FieldTerminalPath {
	return &ListAccessPointsRequest_FieldTerminalPath{selector: ListAccessPointsRequest_FieldPathSelectorView}
}

func (s ListAccessPointsRequestPathSelectorView) WithValue(value view.View) *ListAccessPointsRequest_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*ListAccessPointsRequest_FieldTerminalPathValue)
}

func (s ListAccessPointsRequestPathSelectorView) WithArrayOfValues(values []view.View) *ListAccessPointsRequest_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*ListAccessPointsRequest_FieldTerminalPathArrayOfValues)
}

type ListAccessPointsResponseFieldPathBuilder struct{}

func NewListAccessPointsResponseFieldPathBuilder() ListAccessPointsResponseFieldPathBuilder {
	return ListAccessPointsResponseFieldPathBuilder{}
}
func (ListAccessPointsResponseFieldPathBuilder) AccessPoints() ListAccessPointsResponsePathSelectorAccessPoints {
	return ListAccessPointsResponsePathSelectorAccessPoints{}
}
func (ListAccessPointsResponseFieldPathBuilder) PrevPageToken() ListAccessPointsResponsePathSelectorPrevPageToken {
	return ListAccessPointsResponsePathSelectorPrevPageToken{}
}
func (ListAccessPointsResponseFieldPathBuilder) NextPageToken() ListAccessPointsResponsePathSelectorNextPageToken {
	return ListAccessPointsResponsePathSelectorNextPageToken{}
}

type ListAccessPointsResponsePathSelectorAccessPoints struct{}

func (ListAccessPointsResponsePathSelectorAccessPoints) FieldPath() *ListAccessPointsResponse_FieldTerminalPath {
	return &ListAccessPointsResponse_FieldTerminalPath{selector: ListAccessPointsResponse_FieldPathSelectorAccessPoints}
}

func (s ListAccessPointsResponsePathSelectorAccessPoints) WithValue(value []*access_point.AccessPoint) *ListAccessPointsResponse_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*ListAccessPointsResponse_FieldTerminalPathValue)
}

func (s ListAccessPointsResponsePathSelectorAccessPoints) WithArrayOfValues(values [][]*access_point.AccessPoint) *ListAccessPointsResponse_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*ListAccessPointsResponse_FieldTerminalPathArrayOfValues)
}

func (s ListAccessPointsResponsePathSelectorAccessPoints) WithItemValue(value *access_point.AccessPoint) *ListAccessPointsResponse_FieldTerminalPathArrayItemValue {
	return s.FieldPath().WithIArrayItemValue(value).(*ListAccessPointsResponse_FieldTerminalPathArrayItemValue)
}
func (ListAccessPointsResponsePathSelectorAccessPoints) WithSubPath(subPath access_point.AccessPoint_FieldPath) *ListAccessPointsResponse_FieldSubPath {
	return &ListAccessPointsResponse_FieldSubPath{selector: ListAccessPointsResponse_FieldPathSelectorAccessPoints, subPath: subPath}
}

func (s ListAccessPointsResponsePathSelectorAccessPoints) WithSubValue(subPathValue access_point.AccessPoint_FieldPathValue) *ListAccessPointsResponse_FieldSubPathValue {
	return &ListAccessPointsResponse_FieldSubPathValue{ListAccessPointsResponse_FieldPath: s.WithSubPath(subPathValue), subPathValue: subPathValue}
}

func (s ListAccessPointsResponsePathSelectorAccessPoints) WithSubArrayOfValues(subPathArrayOfValues access_point.AccessPoint_FieldPathArrayOfValues) *ListAccessPointsResponse_FieldSubPathArrayOfValues {
	return &ListAccessPointsResponse_FieldSubPathArrayOfValues{ListAccessPointsResponse_FieldPath: s.WithSubPath(subPathArrayOfValues), subPathArrayOfValues: subPathArrayOfValues}
}

func (s ListAccessPointsResponsePathSelectorAccessPoints) WithSubArrayItemValue(subPathArrayItemValue access_point.AccessPoint_FieldPathArrayItemValue) *ListAccessPointsResponse_FieldSubPathArrayItemValue {
	return &ListAccessPointsResponse_FieldSubPathArrayItemValue{ListAccessPointsResponse_FieldPath: s.WithSubPath(subPathArrayItemValue), subPathItemValue: subPathArrayItemValue}
}

func (ListAccessPointsResponsePathSelectorAccessPoints) Name() ListAccessPointsResponsePathSelectorAccessPointsName {
	return ListAccessPointsResponsePathSelectorAccessPointsName{}
}

type ListAccessPointsResponsePathSelectorAccessPointsName struct{}

func (ListAccessPointsResponsePathSelectorAccessPointsName) FieldPath() *ListAccessPointsResponse_FieldSubPath {
	return &ListAccessPointsResponse_FieldSubPath{
		selector: ListAccessPointsResponse_FieldPathSelectorAccessPoints,
		subPath:  access_point.NewAccessPointFieldPathBuilder().Name().FieldPath(),
	}
}

func (s ListAccessPointsResponsePathSelectorAccessPointsName) WithValue(value *access_point.Name) *ListAccessPointsResponse_FieldSubPathValue {
	return s.FieldPath().WithIValue(value).(*ListAccessPointsResponse_FieldSubPathValue)
}

func (s ListAccessPointsResponsePathSelectorAccessPointsName) WithArrayOfValues(values []*access_point.Name) *ListAccessPointsResponse_FieldSubPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*ListAccessPointsResponse_FieldSubPathArrayOfValues)
}

type ListAccessPointsResponsePathSelectorPrevPageToken struct{}

func (ListAccessPointsResponsePathSelectorPrevPageToken) FieldPath() *ListAccessPointsResponse_FieldTerminalPath {
	return &ListAccessPointsResponse_FieldTerminalPath{selector: ListAccessPointsResponse_FieldPathSelectorPrevPageToken}
}

func (s ListAccessPointsResponsePathSelectorPrevPageToken) WithValue(value *access_point.PagerCursor) *ListAccessPointsResponse_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*ListAccessPointsResponse_FieldTerminalPathValue)
}

func (s ListAccessPointsResponsePathSelectorPrevPageToken) WithArrayOfValues(values []*access_point.PagerCursor) *ListAccessPointsResponse_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*ListAccessPointsResponse_FieldTerminalPathArrayOfValues)
}

type ListAccessPointsResponsePathSelectorNextPageToken struct{}

func (ListAccessPointsResponsePathSelectorNextPageToken) FieldPath() *ListAccessPointsResponse_FieldTerminalPath {
	return &ListAccessPointsResponse_FieldTerminalPath{selector: ListAccessPointsResponse_FieldPathSelectorNextPageToken}
}

func (s ListAccessPointsResponsePathSelectorNextPageToken) WithValue(value *access_point.PagerCursor) *ListAccessPointsResponse_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*ListAccessPointsResponse_FieldTerminalPathValue)
}

func (s ListAccessPointsResponsePathSelectorNextPageToken) WithArrayOfValues(values []*access_point.PagerCursor) *ListAccessPointsResponse_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*ListAccessPointsResponse_FieldTerminalPathArrayOfValues)
}

type WatchAccessPointRequestFieldPathBuilder struct{}

func NewWatchAccessPointRequestFieldPathBuilder() WatchAccessPointRequestFieldPathBuilder {
	return WatchAccessPointRequestFieldPathBuilder{}
}
func (WatchAccessPointRequestFieldPathBuilder) Name() WatchAccessPointRequestPathSelectorName {
	return WatchAccessPointRequestPathSelectorName{}
}
func (WatchAccessPointRequestFieldPathBuilder) FieldMask() WatchAccessPointRequestPathSelectorFieldMask {
	return WatchAccessPointRequestPathSelectorFieldMask{}
}
func (WatchAccessPointRequestFieldPathBuilder) View() WatchAccessPointRequestPathSelectorView {
	return WatchAccessPointRequestPathSelectorView{}
}

type WatchAccessPointRequestPathSelectorName struct{}

func (WatchAccessPointRequestPathSelectorName) FieldPath() *WatchAccessPointRequest_FieldTerminalPath {
	return &WatchAccessPointRequest_FieldTerminalPath{selector: WatchAccessPointRequest_FieldPathSelectorName}
}

func (s WatchAccessPointRequestPathSelectorName) WithValue(value *access_point.Reference) *WatchAccessPointRequest_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*WatchAccessPointRequest_FieldTerminalPathValue)
}

func (s WatchAccessPointRequestPathSelectorName) WithArrayOfValues(values []*access_point.Reference) *WatchAccessPointRequest_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*WatchAccessPointRequest_FieldTerminalPathArrayOfValues)
}

type WatchAccessPointRequestPathSelectorFieldMask struct{}

func (WatchAccessPointRequestPathSelectorFieldMask) FieldPath() *WatchAccessPointRequest_FieldTerminalPath {
	return &WatchAccessPointRequest_FieldTerminalPath{selector: WatchAccessPointRequest_FieldPathSelectorFieldMask}
}

func (s WatchAccessPointRequestPathSelectorFieldMask) WithValue(value *access_point.AccessPoint_FieldMask) *WatchAccessPointRequest_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*WatchAccessPointRequest_FieldTerminalPathValue)
}

func (s WatchAccessPointRequestPathSelectorFieldMask) WithArrayOfValues(values []*access_point.AccessPoint_FieldMask) *WatchAccessPointRequest_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*WatchAccessPointRequest_FieldTerminalPathArrayOfValues)
}

type WatchAccessPointRequestPathSelectorView struct{}

func (WatchAccessPointRequestPathSelectorView) FieldPath() *WatchAccessPointRequest_FieldTerminalPath {
	return &WatchAccessPointRequest_FieldTerminalPath{selector: WatchAccessPointRequest_FieldPathSelectorView}
}

func (s WatchAccessPointRequestPathSelectorView) WithValue(value view.View) *WatchAccessPointRequest_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*WatchAccessPointRequest_FieldTerminalPathValue)
}

func (s WatchAccessPointRequestPathSelectorView) WithArrayOfValues(values []view.View) *WatchAccessPointRequest_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*WatchAccessPointRequest_FieldTerminalPathArrayOfValues)
}

type WatchAccessPointResponseFieldPathBuilder struct{}

func NewWatchAccessPointResponseFieldPathBuilder() WatchAccessPointResponseFieldPathBuilder {
	return WatchAccessPointResponseFieldPathBuilder{}
}
func (WatchAccessPointResponseFieldPathBuilder) Change() WatchAccessPointResponsePathSelectorChange {
	return WatchAccessPointResponsePathSelectorChange{}
}

type WatchAccessPointResponsePathSelectorChange struct{}

func (WatchAccessPointResponsePathSelectorChange) FieldPath() *WatchAccessPointResponse_FieldTerminalPath {
	return &WatchAccessPointResponse_FieldTerminalPath{selector: WatchAccessPointResponse_FieldPathSelectorChange}
}

func (s WatchAccessPointResponsePathSelectorChange) WithValue(value *access_point.AccessPointChange) *WatchAccessPointResponse_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*WatchAccessPointResponse_FieldTerminalPathValue)
}

func (s WatchAccessPointResponsePathSelectorChange) WithArrayOfValues(values []*access_point.AccessPointChange) *WatchAccessPointResponse_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*WatchAccessPointResponse_FieldTerminalPathArrayOfValues)
}

type WatchAccessPointsRequestFieldPathBuilder struct{}

func NewWatchAccessPointsRequestFieldPathBuilder() WatchAccessPointsRequestFieldPathBuilder {
	return WatchAccessPointsRequestFieldPathBuilder{}
}
func (WatchAccessPointsRequestFieldPathBuilder) Type() WatchAccessPointsRequestPathSelectorType {
	return WatchAccessPointsRequestPathSelectorType{}
}
func (WatchAccessPointsRequestFieldPathBuilder) Parent() WatchAccessPointsRequestPathSelectorParent {
	return WatchAccessPointsRequestPathSelectorParent{}
}
func (WatchAccessPointsRequestFieldPathBuilder) PageSize() WatchAccessPointsRequestPathSelectorPageSize {
	return WatchAccessPointsRequestPathSelectorPageSize{}
}
func (WatchAccessPointsRequestFieldPathBuilder) PageToken() WatchAccessPointsRequestPathSelectorPageToken {
	return WatchAccessPointsRequestPathSelectorPageToken{}
}
func (WatchAccessPointsRequestFieldPathBuilder) OrderBy() WatchAccessPointsRequestPathSelectorOrderBy {
	return WatchAccessPointsRequestPathSelectorOrderBy{}
}
func (WatchAccessPointsRequestFieldPathBuilder) ResumeToken() WatchAccessPointsRequestPathSelectorResumeToken {
	return WatchAccessPointsRequestPathSelectorResumeToken{}
}
func (WatchAccessPointsRequestFieldPathBuilder) Filter() WatchAccessPointsRequestPathSelectorFilter {
	return WatchAccessPointsRequestPathSelectorFilter{}
}
func (WatchAccessPointsRequestFieldPathBuilder) FieldMask() WatchAccessPointsRequestPathSelectorFieldMask {
	return WatchAccessPointsRequestPathSelectorFieldMask{}
}
func (WatchAccessPointsRequestFieldPathBuilder) View() WatchAccessPointsRequestPathSelectorView {
	return WatchAccessPointsRequestPathSelectorView{}
}
func (WatchAccessPointsRequestFieldPathBuilder) MaxChunkSize() WatchAccessPointsRequestPathSelectorMaxChunkSize {
	return WatchAccessPointsRequestPathSelectorMaxChunkSize{}
}

type WatchAccessPointsRequestPathSelectorType struct{}

func (WatchAccessPointsRequestPathSelectorType) FieldPath() *WatchAccessPointsRequest_FieldTerminalPath {
	return &WatchAccessPointsRequest_FieldTerminalPath{selector: WatchAccessPointsRequest_FieldPathSelectorType}
}

func (s WatchAccessPointsRequestPathSelectorType) WithValue(value watch_type.WatchType) *WatchAccessPointsRequest_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*WatchAccessPointsRequest_FieldTerminalPathValue)
}

func (s WatchAccessPointsRequestPathSelectorType) WithArrayOfValues(values []watch_type.WatchType) *WatchAccessPointsRequest_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*WatchAccessPointsRequest_FieldTerminalPathArrayOfValues)
}

type WatchAccessPointsRequestPathSelectorParent struct{}

func (WatchAccessPointsRequestPathSelectorParent) FieldPath() *WatchAccessPointsRequest_FieldTerminalPath {
	return &WatchAccessPointsRequest_FieldTerminalPath{selector: WatchAccessPointsRequest_FieldPathSelectorParent}
}

func (s WatchAccessPointsRequestPathSelectorParent) WithValue(value *access_point.ParentReference) *WatchAccessPointsRequest_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*WatchAccessPointsRequest_FieldTerminalPathValue)
}

func (s WatchAccessPointsRequestPathSelectorParent) WithArrayOfValues(values []*access_point.ParentReference) *WatchAccessPointsRequest_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*WatchAccessPointsRequest_FieldTerminalPathArrayOfValues)
}

type WatchAccessPointsRequestPathSelectorPageSize struct{}

func (WatchAccessPointsRequestPathSelectorPageSize) FieldPath() *WatchAccessPointsRequest_FieldTerminalPath {
	return &WatchAccessPointsRequest_FieldTerminalPath{selector: WatchAccessPointsRequest_FieldPathSelectorPageSize}
}

func (s WatchAccessPointsRequestPathSelectorPageSize) WithValue(value int32) *WatchAccessPointsRequest_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*WatchAccessPointsRequest_FieldTerminalPathValue)
}

func (s WatchAccessPointsRequestPathSelectorPageSize) WithArrayOfValues(values []int32) *WatchAccessPointsRequest_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*WatchAccessPointsRequest_FieldTerminalPathArrayOfValues)
}

type WatchAccessPointsRequestPathSelectorPageToken struct{}

func (WatchAccessPointsRequestPathSelectorPageToken) FieldPath() *WatchAccessPointsRequest_FieldTerminalPath {
	return &WatchAccessPointsRequest_FieldTerminalPath{selector: WatchAccessPointsRequest_FieldPathSelectorPageToken}
}

func (s WatchAccessPointsRequestPathSelectorPageToken) WithValue(value *access_point.PagerCursor) *WatchAccessPointsRequest_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*WatchAccessPointsRequest_FieldTerminalPathValue)
}

func (s WatchAccessPointsRequestPathSelectorPageToken) WithArrayOfValues(values []*access_point.PagerCursor) *WatchAccessPointsRequest_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*WatchAccessPointsRequest_FieldTerminalPathArrayOfValues)
}

type WatchAccessPointsRequestPathSelectorOrderBy struct{}

func (WatchAccessPointsRequestPathSelectorOrderBy) FieldPath() *WatchAccessPointsRequest_FieldTerminalPath {
	return &WatchAccessPointsRequest_FieldTerminalPath{selector: WatchAccessPointsRequest_FieldPathSelectorOrderBy}
}

func (s WatchAccessPointsRequestPathSelectorOrderBy) WithValue(value *access_point.OrderBy) *WatchAccessPointsRequest_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*WatchAccessPointsRequest_FieldTerminalPathValue)
}

func (s WatchAccessPointsRequestPathSelectorOrderBy) WithArrayOfValues(values []*access_point.OrderBy) *WatchAccessPointsRequest_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*WatchAccessPointsRequest_FieldTerminalPathArrayOfValues)
}

type WatchAccessPointsRequestPathSelectorResumeToken struct{}

func (WatchAccessPointsRequestPathSelectorResumeToken) FieldPath() *WatchAccessPointsRequest_FieldTerminalPath {
	return &WatchAccessPointsRequest_FieldTerminalPath{selector: WatchAccessPointsRequest_FieldPathSelectorResumeToken}
}

func (s WatchAccessPointsRequestPathSelectorResumeToken) WithValue(value string) *WatchAccessPointsRequest_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*WatchAccessPointsRequest_FieldTerminalPathValue)
}

func (s WatchAccessPointsRequestPathSelectorResumeToken) WithArrayOfValues(values []string) *WatchAccessPointsRequest_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*WatchAccessPointsRequest_FieldTerminalPathArrayOfValues)
}

type WatchAccessPointsRequestPathSelectorFilter struct{}

func (WatchAccessPointsRequestPathSelectorFilter) FieldPath() *WatchAccessPointsRequest_FieldTerminalPath {
	return &WatchAccessPointsRequest_FieldTerminalPath{selector: WatchAccessPointsRequest_FieldPathSelectorFilter}
}

func (s WatchAccessPointsRequestPathSelectorFilter) WithValue(value *access_point.Filter) *WatchAccessPointsRequest_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*WatchAccessPointsRequest_FieldTerminalPathValue)
}

func (s WatchAccessPointsRequestPathSelectorFilter) WithArrayOfValues(values []*access_point.Filter) *WatchAccessPointsRequest_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*WatchAccessPointsRequest_FieldTerminalPathArrayOfValues)
}

type WatchAccessPointsRequestPathSelectorFieldMask struct{}

func (WatchAccessPointsRequestPathSelectorFieldMask) FieldPath() *WatchAccessPointsRequest_FieldTerminalPath {
	return &WatchAccessPointsRequest_FieldTerminalPath{selector: WatchAccessPointsRequest_FieldPathSelectorFieldMask}
}

func (s WatchAccessPointsRequestPathSelectorFieldMask) WithValue(value *access_point.AccessPoint_FieldMask) *WatchAccessPointsRequest_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*WatchAccessPointsRequest_FieldTerminalPathValue)
}

func (s WatchAccessPointsRequestPathSelectorFieldMask) WithArrayOfValues(values []*access_point.AccessPoint_FieldMask) *WatchAccessPointsRequest_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*WatchAccessPointsRequest_FieldTerminalPathArrayOfValues)
}

type WatchAccessPointsRequestPathSelectorView struct{}

func (WatchAccessPointsRequestPathSelectorView) FieldPath() *WatchAccessPointsRequest_FieldTerminalPath {
	return &WatchAccessPointsRequest_FieldTerminalPath{selector: WatchAccessPointsRequest_FieldPathSelectorView}
}

func (s WatchAccessPointsRequestPathSelectorView) WithValue(value view.View) *WatchAccessPointsRequest_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*WatchAccessPointsRequest_FieldTerminalPathValue)
}

func (s WatchAccessPointsRequestPathSelectorView) WithArrayOfValues(values []view.View) *WatchAccessPointsRequest_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*WatchAccessPointsRequest_FieldTerminalPathArrayOfValues)
}

type WatchAccessPointsRequestPathSelectorMaxChunkSize struct{}

func (WatchAccessPointsRequestPathSelectorMaxChunkSize) FieldPath() *WatchAccessPointsRequest_FieldTerminalPath {
	return &WatchAccessPointsRequest_FieldTerminalPath{selector: WatchAccessPointsRequest_FieldPathSelectorMaxChunkSize}
}

func (s WatchAccessPointsRequestPathSelectorMaxChunkSize) WithValue(value int32) *WatchAccessPointsRequest_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*WatchAccessPointsRequest_FieldTerminalPathValue)
}

func (s WatchAccessPointsRequestPathSelectorMaxChunkSize) WithArrayOfValues(values []int32) *WatchAccessPointsRequest_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*WatchAccessPointsRequest_FieldTerminalPathArrayOfValues)
}

type WatchAccessPointsResponseFieldPathBuilder struct{}

func NewWatchAccessPointsResponseFieldPathBuilder() WatchAccessPointsResponseFieldPathBuilder {
	return WatchAccessPointsResponseFieldPathBuilder{}
}
func (WatchAccessPointsResponseFieldPathBuilder) AccessPointChanges() WatchAccessPointsResponsePathSelectorAccessPointChanges {
	return WatchAccessPointsResponsePathSelectorAccessPointChanges{}
}
func (WatchAccessPointsResponseFieldPathBuilder) IsCurrent() WatchAccessPointsResponsePathSelectorIsCurrent {
	return WatchAccessPointsResponsePathSelectorIsCurrent{}
}
func (WatchAccessPointsResponseFieldPathBuilder) PageTokenChange() WatchAccessPointsResponsePathSelectorPageTokenChange {
	return WatchAccessPointsResponsePathSelectorPageTokenChange{}
}
func (WatchAccessPointsResponseFieldPathBuilder) ResumeToken() WatchAccessPointsResponsePathSelectorResumeToken {
	return WatchAccessPointsResponsePathSelectorResumeToken{}
}
func (WatchAccessPointsResponseFieldPathBuilder) SnapshotSize() WatchAccessPointsResponsePathSelectorSnapshotSize {
	return WatchAccessPointsResponsePathSelectorSnapshotSize{}
}
func (WatchAccessPointsResponseFieldPathBuilder) IsSoftReset() WatchAccessPointsResponsePathSelectorIsSoftReset {
	return WatchAccessPointsResponsePathSelectorIsSoftReset{}
}
func (WatchAccessPointsResponseFieldPathBuilder) IsHardReset() WatchAccessPointsResponsePathSelectorIsHardReset {
	return WatchAccessPointsResponsePathSelectorIsHardReset{}
}

type WatchAccessPointsResponsePathSelectorAccessPointChanges struct{}

func (WatchAccessPointsResponsePathSelectorAccessPointChanges) FieldPath() *WatchAccessPointsResponse_FieldTerminalPath {
	return &WatchAccessPointsResponse_FieldTerminalPath{selector: WatchAccessPointsResponse_FieldPathSelectorAccessPointChanges}
}

func (s WatchAccessPointsResponsePathSelectorAccessPointChanges) WithValue(value []*access_point.AccessPointChange) *WatchAccessPointsResponse_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*WatchAccessPointsResponse_FieldTerminalPathValue)
}

func (s WatchAccessPointsResponsePathSelectorAccessPointChanges) WithArrayOfValues(values [][]*access_point.AccessPointChange) *WatchAccessPointsResponse_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*WatchAccessPointsResponse_FieldTerminalPathArrayOfValues)
}

func (s WatchAccessPointsResponsePathSelectorAccessPointChanges) WithItemValue(value *access_point.AccessPointChange) *WatchAccessPointsResponse_FieldTerminalPathArrayItemValue {
	return s.FieldPath().WithIArrayItemValue(value).(*WatchAccessPointsResponse_FieldTerminalPathArrayItemValue)
}

type WatchAccessPointsResponsePathSelectorIsCurrent struct{}

func (WatchAccessPointsResponsePathSelectorIsCurrent) FieldPath() *WatchAccessPointsResponse_FieldTerminalPath {
	return &WatchAccessPointsResponse_FieldTerminalPath{selector: WatchAccessPointsResponse_FieldPathSelectorIsCurrent}
}

func (s WatchAccessPointsResponsePathSelectorIsCurrent) WithValue(value bool) *WatchAccessPointsResponse_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*WatchAccessPointsResponse_FieldTerminalPathValue)
}

func (s WatchAccessPointsResponsePathSelectorIsCurrent) WithArrayOfValues(values []bool) *WatchAccessPointsResponse_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*WatchAccessPointsResponse_FieldTerminalPathArrayOfValues)
}

type WatchAccessPointsResponsePathSelectorPageTokenChange struct{}

func (WatchAccessPointsResponsePathSelectorPageTokenChange) FieldPath() *WatchAccessPointsResponse_FieldTerminalPath {
	return &WatchAccessPointsResponse_FieldTerminalPath{selector: WatchAccessPointsResponse_FieldPathSelectorPageTokenChange}
}

func (s WatchAccessPointsResponsePathSelectorPageTokenChange) WithValue(value *WatchAccessPointsResponse_PageTokenChange) *WatchAccessPointsResponse_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*WatchAccessPointsResponse_FieldTerminalPathValue)
}

func (s WatchAccessPointsResponsePathSelectorPageTokenChange) WithArrayOfValues(values []*WatchAccessPointsResponse_PageTokenChange) *WatchAccessPointsResponse_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*WatchAccessPointsResponse_FieldTerminalPathArrayOfValues)
}

func (WatchAccessPointsResponsePathSelectorPageTokenChange) WithSubPath(subPath WatchAccessPointsResponsePageTokenChange_FieldPath) *WatchAccessPointsResponse_FieldSubPath {
	return &WatchAccessPointsResponse_FieldSubPath{selector: WatchAccessPointsResponse_FieldPathSelectorPageTokenChange, subPath: subPath}
}

func (s WatchAccessPointsResponsePathSelectorPageTokenChange) WithSubValue(subPathValue WatchAccessPointsResponsePageTokenChange_FieldPathValue) *WatchAccessPointsResponse_FieldSubPathValue {
	return &WatchAccessPointsResponse_FieldSubPathValue{WatchAccessPointsResponse_FieldPath: s.WithSubPath(subPathValue), subPathValue: subPathValue}
}

func (s WatchAccessPointsResponsePathSelectorPageTokenChange) WithSubArrayOfValues(subPathArrayOfValues WatchAccessPointsResponsePageTokenChange_FieldPathArrayOfValues) *WatchAccessPointsResponse_FieldSubPathArrayOfValues {
	return &WatchAccessPointsResponse_FieldSubPathArrayOfValues{WatchAccessPointsResponse_FieldPath: s.WithSubPath(subPathArrayOfValues), subPathArrayOfValues: subPathArrayOfValues}
}

func (s WatchAccessPointsResponsePathSelectorPageTokenChange) WithSubArrayItemValue(subPathArrayItemValue WatchAccessPointsResponsePageTokenChange_FieldPathArrayItemValue) *WatchAccessPointsResponse_FieldSubPathArrayItemValue {
	return &WatchAccessPointsResponse_FieldSubPathArrayItemValue{WatchAccessPointsResponse_FieldPath: s.WithSubPath(subPathArrayItemValue), subPathItemValue: subPathArrayItemValue}
}

func (WatchAccessPointsResponsePathSelectorPageTokenChange) PrevPageToken() WatchAccessPointsResponsePathSelectorPageTokenChangePrevPageToken {
	return WatchAccessPointsResponsePathSelectorPageTokenChangePrevPageToken{}
}

func (WatchAccessPointsResponsePathSelectorPageTokenChange) NextPageToken() WatchAccessPointsResponsePathSelectorPageTokenChangeNextPageToken {
	return WatchAccessPointsResponsePathSelectorPageTokenChangeNextPageToken{}
}

type WatchAccessPointsResponsePathSelectorPageTokenChangePrevPageToken struct{}

func (WatchAccessPointsResponsePathSelectorPageTokenChangePrevPageToken) FieldPath() *WatchAccessPointsResponse_FieldSubPath {
	return &WatchAccessPointsResponse_FieldSubPath{
		selector: WatchAccessPointsResponse_FieldPathSelectorPageTokenChange,
		subPath:  NewWatchAccessPointsResponsePageTokenChangeFieldPathBuilder().PrevPageToken().FieldPath(),
	}
}

func (s WatchAccessPointsResponsePathSelectorPageTokenChangePrevPageToken) WithValue(value *access_point.PagerCursor) *WatchAccessPointsResponse_FieldSubPathValue {
	return s.FieldPath().WithIValue(value).(*WatchAccessPointsResponse_FieldSubPathValue)
}

func (s WatchAccessPointsResponsePathSelectorPageTokenChangePrevPageToken) WithArrayOfValues(values []*access_point.PagerCursor) *WatchAccessPointsResponse_FieldSubPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*WatchAccessPointsResponse_FieldSubPathArrayOfValues)
}

type WatchAccessPointsResponsePathSelectorPageTokenChangeNextPageToken struct{}

func (WatchAccessPointsResponsePathSelectorPageTokenChangeNextPageToken) FieldPath() *WatchAccessPointsResponse_FieldSubPath {
	return &WatchAccessPointsResponse_FieldSubPath{
		selector: WatchAccessPointsResponse_FieldPathSelectorPageTokenChange,
		subPath:  NewWatchAccessPointsResponsePageTokenChangeFieldPathBuilder().NextPageToken().FieldPath(),
	}
}

func (s WatchAccessPointsResponsePathSelectorPageTokenChangeNextPageToken) WithValue(value *access_point.PagerCursor) *WatchAccessPointsResponse_FieldSubPathValue {
	return s.FieldPath().WithIValue(value).(*WatchAccessPointsResponse_FieldSubPathValue)
}

func (s WatchAccessPointsResponsePathSelectorPageTokenChangeNextPageToken) WithArrayOfValues(values []*access_point.PagerCursor) *WatchAccessPointsResponse_FieldSubPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*WatchAccessPointsResponse_FieldSubPathArrayOfValues)
}

type WatchAccessPointsResponsePathSelectorResumeToken struct{}

func (WatchAccessPointsResponsePathSelectorResumeToken) FieldPath() *WatchAccessPointsResponse_FieldTerminalPath {
	return &WatchAccessPointsResponse_FieldTerminalPath{selector: WatchAccessPointsResponse_FieldPathSelectorResumeToken}
}

func (s WatchAccessPointsResponsePathSelectorResumeToken) WithValue(value string) *WatchAccessPointsResponse_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*WatchAccessPointsResponse_FieldTerminalPathValue)
}

func (s WatchAccessPointsResponsePathSelectorResumeToken) WithArrayOfValues(values []string) *WatchAccessPointsResponse_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*WatchAccessPointsResponse_FieldTerminalPathArrayOfValues)
}

type WatchAccessPointsResponsePathSelectorSnapshotSize struct{}

func (WatchAccessPointsResponsePathSelectorSnapshotSize) FieldPath() *WatchAccessPointsResponse_FieldTerminalPath {
	return &WatchAccessPointsResponse_FieldTerminalPath{selector: WatchAccessPointsResponse_FieldPathSelectorSnapshotSize}
}

func (s WatchAccessPointsResponsePathSelectorSnapshotSize) WithValue(value int64) *WatchAccessPointsResponse_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*WatchAccessPointsResponse_FieldTerminalPathValue)
}

func (s WatchAccessPointsResponsePathSelectorSnapshotSize) WithArrayOfValues(values []int64) *WatchAccessPointsResponse_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*WatchAccessPointsResponse_FieldTerminalPathArrayOfValues)
}

type WatchAccessPointsResponsePathSelectorIsSoftReset struct{}

func (WatchAccessPointsResponsePathSelectorIsSoftReset) FieldPath() *WatchAccessPointsResponse_FieldTerminalPath {
	return &WatchAccessPointsResponse_FieldTerminalPath{selector: WatchAccessPointsResponse_FieldPathSelectorIsSoftReset}
}

func (s WatchAccessPointsResponsePathSelectorIsSoftReset) WithValue(value bool) *WatchAccessPointsResponse_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*WatchAccessPointsResponse_FieldTerminalPathValue)
}

func (s WatchAccessPointsResponsePathSelectorIsSoftReset) WithArrayOfValues(values []bool) *WatchAccessPointsResponse_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*WatchAccessPointsResponse_FieldTerminalPathArrayOfValues)
}

type WatchAccessPointsResponsePathSelectorIsHardReset struct{}

func (WatchAccessPointsResponsePathSelectorIsHardReset) FieldPath() *WatchAccessPointsResponse_FieldTerminalPath {
	return &WatchAccessPointsResponse_FieldTerminalPath{selector: WatchAccessPointsResponse_FieldPathSelectorIsHardReset}
}

func (s WatchAccessPointsResponsePathSelectorIsHardReset) WithValue(value bool) *WatchAccessPointsResponse_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*WatchAccessPointsResponse_FieldTerminalPathValue)
}

func (s WatchAccessPointsResponsePathSelectorIsHardReset) WithArrayOfValues(values []bool) *WatchAccessPointsResponse_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*WatchAccessPointsResponse_FieldTerminalPathArrayOfValues)
}

type WatchAccessPointsResponsePageTokenChangeFieldPathBuilder struct{}

func NewWatchAccessPointsResponsePageTokenChangeFieldPathBuilder() WatchAccessPointsResponsePageTokenChangeFieldPathBuilder {
	return WatchAccessPointsResponsePageTokenChangeFieldPathBuilder{}
}
func (WatchAccessPointsResponsePageTokenChangeFieldPathBuilder) PrevPageToken() WatchAccessPointsResponse_PageTokenChangePathSelectorPrevPageToken {
	return WatchAccessPointsResponse_PageTokenChangePathSelectorPrevPageToken{}
}
func (WatchAccessPointsResponsePageTokenChangeFieldPathBuilder) NextPageToken() WatchAccessPointsResponse_PageTokenChangePathSelectorNextPageToken {
	return WatchAccessPointsResponse_PageTokenChangePathSelectorNextPageToken{}
}

type WatchAccessPointsResponse_PageTokenChangePathSelectorPrevPageToken struct{}

func (WatchAccessPointsResponse_PageTokenChangePathSelectorPrevPageToken) FieldPath() *WatchAccessPointsResponsePageTokenChange_FieldTerminalPath {
	return &WatchAccessPointsResponsePageTokenChange_FieldTerminalPath{selector: WatchAccessPointsResponsePageTokenChange_FieldPathSelectorPrevPageToken}
}

func (s WatchAccessPointsResponse_PageTokenChangePathSelectorPrevPageToken) WithValue(value *access_point.PagerCursor) *WatchAccessPointsResponsePageTokenChange_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*WatchAccessPointsResponsePageTokenChange_FieldTerminalPathValue)
}

func (s WatchAccessPointsResponse_PageTokenChangePathSelectorPrevPageToken) WithArrayOfValues(values []*access_point.PagerCursor) *WatchAccessPointsResponsePageTokenChange_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*WatchAccessPointsResponsePageTokenChange_FieldTerminalPathArrayOfValues)
}

type WatchAccessPointsResponse_PageTokenChangePathSelectorNextPageToken struct{}

func (WatchAccessPointsResponse_PageTokenChangePathSelectorNextPageToken) FieldPath() *WatchAccessPointsResponsePageTokenChange_FieldTerminalPath {
	return &WatchAccessPointsResponsePageTokenChange_FieldTerminalPath{selector: WatchAccessPointsResponsePageTokenChange_FieldPathSelectorNextPageToken}
}

func (s WatchAccessPointsResponse_PageTokenChangePathSelectorNextPageToken) WithValue(value *access_point.PagerCursor) *WatchAccessPointsResponsePageTokenChange_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*WatchAccessPointsResponsePageTokenChange_FieldTerminalPathValue)
}

func (s WatchAccessPointsResponse_PageTokenChangePathSelectorNextPageToken) WithArrayOfValues(values []*access_point.PagerCursor) *WatchAccessPointsResponsePageTokenChange_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*WatchAccessPointsResponsePageTokenChange_FieldTerminalPathArrayOfValues)
}

type CreateAccessPointRequestFieldPathBuilder struct{}

func NewCreateAccessPointRequestFieldPathBuilder() CreateAccessPointRequestFieldPathBuilder {
	return CreateAccessPointRequestFieldPathBuilder{}
}
func (CreateAccessPointRequestFieldPathBuilder) Parent() CreateAccessPointRequestPathSelectorParent {
	return CreateAccessPointRequestPathSelectorParent{}
}
func (CreateAccessPointRequestFieldPathBuilder) AccessPoint() CreateAccessPointRequestPathSelectorAccessPoint {
	return CreateAccessPointRequestPathSelectorAccessPoint{}
}

type CreateAccessPointRequestPathSelectorParent struct{}

func (CreateAccessPointRequestPathSelectorParent) FieldPath() *CreateAccessPointRequest_FieldTerminalPath {
	return &CreateAccessPointRequest_FieldTerminalPath{selector: CreateAccessPointRequest_FieldPathSelectorParent}
}

func (s CreateAccessPointRequestPathSelectorParent) WithValue(value *access_point.ParentReference) *CreateAccessPointRequest_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*CreateAccessPointRequest_FieldTerminalPathValue)
}

func (s CreateAccessPointRequestPathSelectorParent) WithArrayOfValues(values []*access_point.ParentReference) *CreateAccessPointRequest_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*CreateAccessPointRequest_FieldTerminalPathArrayOfValues)
}

type CreateAccessPointRequestPathSelectorAccessPoint struct{}

func (CreateAccessPointRequestPathSelectorAccessPoint) FieldPath() *CreateAccessPointRequest_FieldTerminalPath {
	return &CreateAccessPointRequest_FieldTerminalPath{selector: CreateAccessPointRequest_FieldPathSelectorAccessPoint}
}

func (s CreateAccessPointRequestPathSelectorAccessPoint) WithValue(value *access_point.AccessPoint) *CreateAccessPointRequest_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*CreateAccessPointRequest_FieldTerminalPathValue)
}

func (s CreateAccessPointRequestPathSelectorAccessPoint) WithArrayOfValues(values []*access_point.AccessPoint) *CreateAccessPointRequest_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*CreateAccessPointRequest_FieldTerminalPathArrayOfValues)
}

func (CreateAccessPointRequestPathSelectorAccessPoint) WithSubPath(subPath access_point.AccessPoint_FieldPath) *CreateAccessPointRequest_FieldSubPath {
	return &CreateAccessPointRequest_FieldSubPath{selector: CreateAccessPointRequest_FieldPathSelectorAccessPoint, subPath: subPath}
}

func (s CreateAccessPointRequestPathSelectorAccessPoint) WithSubValue(subPathValue access_point.AccessPoint_FieldPathValue) *CreateAccessPointRequest_FieldSubPathValue {
	return &CreateAccessPointRequest_FieldSubPathValue{CreateAccessPointRequest_FieldPath: s.WithSubPath(subPathValue), subPathValue: subPathValue}
}

func (s CreateAccessPointRequestPathSelectorAccessPoint) WithSubArrayOfValues(subPathArrayOfValues access_point.AccessPoint_FieldPathArrayOfValues) *CreateAccessPointRequest_FieldSubPathArrayOfValues {
	return &CreateAccessPointRequest_FieldSubPathArrayOfValues{CreateAccessPointRequest_FieldPath: s.WithSubPath(subPathArrayOfValues), subPathArrayOfValues: subPathArrayOfValues}
}

func (s CreateAccessPointRequestPathSelectorAccessPoint) WithSubArrayItemValue(subPathArrayItemValue access_point.AccessPoint_FieldPathArrayItemValue) *CreateAccessPointRequest_FieldSubPathArrayItemValue {
	return &CreateAccessPointRequest_FieldSubPathArrayItemValue{CreateAccessPointRequest_FieldPath: s.WithSubPath(subPathArrayItemValue), subPathItemValue: subPathArrayItemValue}
}

func (CreateAccessPointRequestPathSelectorAccessPoint) Name() CreateAccessPointRequestPathSelectorAccessPointName {
	return CreateAccessPointRequestPathSelectorAccessPointName{}
}

type CreateAccessPointRequestPathSelectorAccessPointName struct{}

func (CreateAccessPointRequestPathSelectorAccessPointName) FieldPath() *CreateAccessPointRequest_FieldSubPath {
	return &CreateAccessPointRequest_FieldSubPath{
		selector: CreateAccessPointRequest_FieldPathSelectorAccessPoint,
		subPath:  access_point.NewAccessPointFieldPathBuilder().Name().FieldPath(),
	}
}

func (s CreateAccessPointRequestPathSelectorAccessPointName) WithValue(value *access_point.Name) *CreateAccessPointRequest_FieldSubPathValue {
	return s.FieldPath().WithIValue(value).(*CreateAccessPointRequest_FieldSubPathValue)
}

func (s CreateAccessPointRequestPathSelectorAccessPointName) WithArrayOfValues(values []*access_point.Name) *CreateAccessPointRequest_FieldSubPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*CreateAccessPointRequest_FieldSubPathArrayOfValues)
}

type UpdateAccessPointRequestFieldPathBuilder struct{}

func NewUpdateAccessPointRequestFieldPathBuilder() UpdateAccessPointRequestFieldPathBuilder {
	return UpdateAccessPointRequestFieldPathBuilder{}
}
func (UpdateAccessPointRequestFieldPathBuilder) AccessPoint() UpdateAccessPointRequestPathSelectorAccessPoint {
	return UpdateAccessPointRequestPathSelectorAccessPoint{}
}
func (UpdateAccessPointRequestFieldPathBuilder) UpdateMask() UpdateAccessPointRequestPathSelectorUpdateMask {
	return UpdateAccessPointRequestPathSelectorUpdateMask{}
}
func (UpdateAccessPointRequestFieldPathBuilder) Cas() UpdateAccessPointRequestPathSelectorCas {
	return UpdateAccessPointRequestPathSelectorCas{}
}

type UpdateAccessPointRequestPathSelectorAccessPoint struct{}

func (UpdateAccessPointRequestPathSelectorAccessPoint) FieldPath() *UpdateAccessPointRequest_FieldTerminalPath {
	return &UpdateAccessPointRequest_FieldTerminalPath{selector: UpdateAccessPointRequest_FieldPathSelectorAccessPoint}
}

func (s UpdateAccessPointRequestPathSelectorAccessPoint) WithValue(value *access_point.AccessPoint) *UpdateAccessPointRequest_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*UpdateAccessPointRequest_FieldTerminalPathValue)
}

func (s UpdateAccessPointRequestPathSelectorAccessPoint) WithArrayOfValues(values []*access_point.AccessPoint) *UpdateAccessPointRequest_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*UpdateAccessPointRequest_FieldTerminalPathArrayOfValues)
}

func (UpdateAccessPointRequestPathSelectorAccessPoint) WithSubPath(subPath access_point.AccessPoint_FieldPath) *UpdateAccessPointRequest_FieldSubPath {
	return &UpdateAccessPointRequest_FieldSubPath{selector: UpdateAccessPointRequest_FieldPathSelectorAccessPoint, subPath: subPath}
}

func (s UpdateAccessPointRequestPathSelectorAccessPoint) WithSubValue(subPathValue access_point.AccessPoint_FieldPathValue) *UpdateAccessPointRequest_FieldSubPathValue {
	return &UpdateAccessPointRequest_FieldSubPathValue{UpdateAccessPointRequest_FieldPath: s.WithSubPath(subPathValue), subPathValue: subPathValue}
}

func (s UpdateAccessPointRequestPathSelectorAccessPoint) WithSubArrayOfValues(subPathArrayOfValues access_point.AccessPoint_FieldPathArrayOfValues) *UpdateAccessPointRequest_FieldSubPathArrayOfValues {
	return &UpdateAccessPointRequest_FieldSubPathArrayOfValues{UpdateAccessPointRequest_FieldPath: s.WithSubPath(subPathArrayOfValues), subPathArrayOfValues: subPathArrayOfValues}
}

func (s UpdateAccessPointRequestPathSelectorAccessPoint) WithSubArrayItemValue(subPathArrayItemValue access_point.AccessPoint_FieldPathArrayItemValue) *UpdateAccessPointRequest_FieldSubPathArrayItemValue {
	return &UpdateAccessPointRequest_FieldSubPathArrayItemValue{UpdateAccessPointRequest_FieldPath: s.WithSubPath(subPathArrayItemValue), subPathItemValue: subPathArrayItemValue}
}

func (UpdateAccessPointRequestPathSelectorAccessPoint) Name() UpdateAccessPointRequestPathSelectorAccessPointName {
	return UpdateAccessPointRequestPathSelectorAccessPointName{}
}

type UpdateAccessPointRequestPathSelectorAccessPointName struct{}

func (UpdateAccessPointRequestPathSelectorAccessPointName) FieldPath() *UpdateAccessPointRequest_FieldSubPath {
	return &UpdateAccessPointRequest_FieldSubPath{
		selector: UpdateAccessPointRequest_FieldPathSelectorAccessPoint,
		subPath:  access_point.NewAccessPointFieldPathBuilder().Name().FieldPath(),
	}
}

func (s UpdateAccessPointRequestPathSelectorAccessPointName) WithValue(value *access_point.Name) *UpdateAccessPointRequest_FieldSubPathValue {
	return s.FieldPath().WithIValue(value).(*UpdateAccessPointRequest_FieldSubPathValue)
}

func (s UpdateAccessPointRequestPathSelectorAccessPointName) WithArrayOfValues(values []*access_point.Name) *UpdateAccessPointRequest_FieldSubPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*UpdateAccessPointRequest_FieldSubPathArrayOfValues)
}

type UpdateAccessPointRequestPathSelectorUpdateMask struct{}

func (UpdateAccessPointRequestPathSelectorUpdateMask) FieldPath() *UpdateAccessPointRequest_FieldTerminalPath {
	return &UpdateAccessPointRequest_FieldTerminalPath{selector: UpdateAccessPointRequest_FieldPathSelectorUpdateMask}
}

func (s UpdateAccessPointRequestPathSelectorUpdateMask) WithValue(value *access_point.AccessPoint_FieldMask) *UpdateAccessPointRequest_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*UpdateAccessPointRequest_FieldTerminalPathValue)
}

func (s UpdateAccessPointRequestPathSelectorUpdateMask) WithArrayOfValues(values []*access_point.AccessPoint_FieldMask) *UpdateAccessPointRequest_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*UpdateAccessPointRequest_FieldTerminalPathArrayOfValues)
}

type UpdateAccessPointRequestPathSelectorCas struct{}

func (UpdateAccessPointRequestPathSelectorCas) FieldPath() *UpdateAccessPointRequest_FieldTerminalPath {
	return &UpdateAccessPointRequest_FieldTerminalPath{selector: UpdateAccessPointRequest_FieldPathSelectorCas}
}

func (s UpdateAccessPointRequestPathSelectorCas) WithValue(value *UpdateAccessPointRequest_CAS) *UpdateAccessPointRequest_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*UpdateAccessPointRequest_FieldTerminalPathValue)
}

func (s UpdateAccessPointRequestPathSelectorCas) WithArrayOfValues(values []*UpdateAccessPointRequest_CAS) *UpdateAccessPointRequest_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*UpdateAccessPointRequest_FieldTerminalPathArrayOfValues)
}

func (UpdateAccessPointRequestPathSelectorCas) WithSubPath(subPath UpdateAccessPointRequestCAS_FieldPath) *UpdateAccessPointRequest_FieldSubPath {
	return &UpdateAccessPointRequest_FieldSubPath{selector: UpdateAccessPointRequest_FieldPathSelectorCas, subPath: subPath}
}

func (s UpdateAccessPointRequestPathSelectorCas) WithSubValue(subPathValue UpdateAccessPointRequestCAS_FieldPathValue) *UpdateAccessPointRequest_FieldSubPathValue {
	return &UpdateAccessPointRequest_FieldSubPathValue{UpdateAccessPointRequest_FieldPath: s.WithSubPath(subPathValue), subPathValue: subPathValue}
}

func (s UpdateAccessPointRequestPathSelectorCas) WithSubArrayOfValues(subPathArrayOfValues UpdateAccessPointRequestCAS_FieldPathArrayOfValues) *UpdateAccessPointRequest_FieldSubPathArrayOfValues {
	return &UpdateAccessPointRequest_FieldSubPathArrayOfValues{UpdateAccessPointRequest_FieldPath: s.WithSubPath(subPathArrayOfValues), subPathArrayOfValues: subPathArrayOfValues}
}

func (s UpdateAccessPointRequestPathSelectorCas) WithSubArrayItemValue(subPathArrayItemValue UpdateAccessPointRequestCAS_FieldPathArrayItemValue) *UpdateAccessPointRequest_FieldSubPathArrayItemValue {
	return &UpdateAccessPointRequest_FieldSubPathArrayItemValue{UpdateAccessPointRequest_FieldPath: s.WithSubPath(subPathArrayItemValue), subPathItemValue: subPathArrayItemValue}
}

func (UpdateAccessPointRequestPathSelectorCas) ConditionalState() UpdateAccessPointRequestPathSelectorCasConditionalState {
	return UpdateAccessPointRequestPathSelectorCasConditionalState{}
}

func (UpdateAccessPointRequestPathSelectorCas) FieldMask() UpdateAccessPointRequestPathSelectorCasFieldMask {
	return UpdateAccessPointRequestPathSelectorCasFieldMask{}
}

type UpdateAccessPointRequestPathSelectorCasConditionalState struct{}

func (UpdateAccessPointRequestPathSelectorCasConditionalState) FieldPath() *UpdateAccessPointRequest_FieldSubPath {
	return &UpdateAccessPointRequest_FieldSubPath{
		selector: UpdateAccessPointRequest_FieldPathSelectorCas,
		subPath:  NewUpdateAccessPointRequestCASFieldPathBuilder().ConditionalState().FieldPath(),
	}
}

func (s UpdateAccessPointRequestPathSelectorCasConditionalState) WithValue(value *access_point.AccessPoint) *UpdateAccessPointRequest_FieldSubPathValue {
	return s.FieldPath().WithIValue(value).(*UpdateAccessPointRequest_FieldSubPathValue)
}

func (s UpdateAccessPointRequestPathSelectorCasConditionalState) WithArrayOfValues(values []*access_point.AccessPoint) *UpdateAccessPointRequest_FieldSubPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*UpdateAccessPointRequest_FieldSubPathArrayOfValues)
}

func (UpdateAccessPointRequestPathSelectorCasConditionalState) Name() UpdateAccessPointRequestPathSelectorCasConditionalStateName {
	return UpdateAccessPointRequestPathSelectorCasConditionalStateName{}
}

type UpdateAccessPointRequestPathSelectorCasConditionalStateName struct{}

func (UpdateAccessPointRequestPathSelectorCasConditionalStateName) FieldPath() *UpdateAccessPointRequest_FieldSubPath {
	return &UpdateAccessPointRequest_FieldSubPath{
		selector: UpdateAccessPointRequest_FieldPathSelectorCas,
		subPath:  NewUpdateAccessPointRequestCASFieldPathBuilder().ConditionalState().Name().FieldPath(),
	}
}

func (s UpdateAccessPointRequestPathSelectorCasConditionalStateName) WithValue(value *access_point.Name) *UpdateAccessPointRequest_FieldSubPathValue {
	return s.FieldPath().WithIValue(value).(*UpdateAccessPointRequest_FieldSubPathValue)
}

func (s UpdateAccessPointRequestPathSelectorCasConditionalStateName) WithArrayOfValues(values []*access_point.Name) *UpdateAccessPointRequest_FieldSubPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*UpdateAccessPointRequest_FieldSubPathArrayOfValues)
}

type UpdateAccessPointRequestPathSelectorCasFieldMask struct{}

func (UpdateAccessPointRequestPathSelectorCasFieldMask) FieldPath() *UpdateAccessPointRequest_FieldSubPath {
	return &UpdateAccessPointRequest_FieldSubPath{
		selector: UpdateAccessPointRequest_FieldPathSelectorCas,
		subPath:  NewUpdateAccessPointRequestCASFieldPathBuilder().FieldMask().FieldPath(),
	}
}

func (s UpdateAccessPointRequestPathSelectorCasFieldMask) WithValue(value *access_point.AccessPoint_FieldMask) *UpdateAccessPointRequest_FieldSubPathValue {
	return s.FieldPath().WithIValue(value).(*UpdateAccessPointRequest_FieldSubPathValue)
}

func (s UpdateAccessPointRequestPathSelectorCasFieldMask) WithArrayOfValues(values []*access_point.AccessPoint_FieldMask) *UpdateAccessPointRequest_FieldSubPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*UpdateAccessPointRequest_FieldSubPathArrayOfValues)
}

type UpdateAccessPointRequestCASFieldPathBuilder struct{}

func NewUpdateAccessPointRequestCASFieldPathBuilder() UpdateAccessPointRequestCASFieldPathBuilder {
	return UpdateAccessPointRequestCASFieldPathBuilder{}
}
func (UpdateAccessPointRequestCASFieldPathBuilder) ConditionalState() UpdateAccessPointRequest_CASPathSelectorConditionalState {
	return UpdateAccessPointRequest_CASPathSelectorConditionalState{}
}
func (UpdateAccessPointRequestCASFieldPathBuilder) FieldMask() UpdateAccessPointRequest_CASPathSelectorFieldMask {
	return UpdateAccessPointRequest_CASPathSelectorFieldMask{}
}

type UpdateAccessPointRequest_CASPathSelectorConditionalState struct{}

func (UpdateAccessPointRequest_CASPathSelectorConditionalState) FieldPath() *UpdateAccessPointRequestCAS_FieldTerminalPath {
	return &UpdateAccessPointRequestCAS_FieldTerminalPath{selector: UpdateAccessPointRequestCAS_FieldPathSelectorConditionalState}
}

func (s UpdateAccessPointRequest_CASPathSelectorConditionalState) WithValue(value *access_point.AccessPoint) *UpdateAccessPointRequestCAS_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*UpdateAccessPointRequestCAS_FieldTerminalPathValue)
}

func (s UpdateAccessPointRequest_CASPathSelectorConditionalState) WithArrayOfValues(values []*access_point.AccessPoint) *UpdateAccessPointRequestCAS_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*UpdateAccessPointRequestCAS_FieldTerminalPathArrayOfValues)
}

func (UpdateAccessPointRequest_CASPathSelectorConditionalState) WithSubPath(subPath access_point.AccessPoint_FieldPath) *UpdateAccessPointRequestCAS_FieldSubPath {
	return &UpdateAccessPointRequestCAS_FieldSubPath{selector: UpdateAccessPointRequestCAS_FieldPathSelectorConditionalState, subPath: subPath}
}

func (s UpdateAccessPointRequest_CASPathSelectorConditionalState) WithSubValue(subPathValue access_point.AccessPoint_FieldPathValue) *UpdateAccessPointRequestCAS_FieldSubPathValue {
	return &UpdateAccessPointRequestCAS_FieldSubPathValue{UpdateAccessPointRequestCAS_FieldPath: s.WithSubPath(subPathValue), subPathValue: subPathValue}
}

func (s UpdateAccessPointRequest_CASPathSelectorConditionalState) WithSubArrayOfValues(subPathArrayOfValues access_point.AccessPoint_FieldPathArrayOfValues) *UpdateAccessPointRequestCAS_FieldSubPathArrayOfValues {
	return &UpdateAccessPointRequestCAS_FieldSubPathArrayOfValues{UpdateAccessPointRequestCAS_FieldPath: s.WithSubPath(subPathArrayOfValues), subPathArrayOfValues: subPathArrayOfValues}
}

func (s UpdateAccessPointRequest_CASPathSelectorConditionalState) WithSubArrayItemValue(subPathArrayItemValue access_point.AccessPoint_FieldPathArrayItemValue) *UpdateAccessPointRequestCAS_FieldSubPathArrayItemValue {
	return &UpdateAccessPointRequestCAS_FieldSubPathArrayItemValue{UpdateAccessPointRequestCAS_FieldPath: s.WithSubPath(subPathArrayItemValue), subPathItemValue: subPathArrayItemValue}
}

func (UpdateAccessPointRequest_CASPathSelectorConditionalState) Name() UpdateAccessPointRequest_CASPathSelectorConditionalStateName {
	return UpdateAccessPointRequest_CASPathSelectorConditionalStateName{}
}

type UpdateAccessPointRequest_CASPathSelectorConditionalStateName struct{}

func (UpdateAccessPointRequest_CASPathSelectorConditionalStateName) FieldPath() *UpdateAccessPointRequestCAS_FieldSubPath {
	return &UpdateAccessPointRequestCAS_FieldSubPath{
		selector: UpdateAccessPointRequestCAS_FieldPathSelectorConditionalState,
		subPath:  access_point.NewAccessPointFieldPathBuilder().Name().FieldPath(),
	}
}

func (s UpdateAccessPointRequest_CASPathSelectorConditionalStateName) WithValue(value *access_point.Name) *UpdateAccessPointRequestCAS_FieldSubPathValue {
	return s.FieldPath().WithIValue(value).(*UpdateAccessPointRequestCAS_FieldSubPathValue)
}

func (s UpdateAccessPointRequest_CASPathSelectorConditionalStateName) WithArrayOfValues(values []*access_point.Name) *UpdateAccessPointRequestCAS_FieldSubPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*UpdateAccessPointRequestCAS_FieldSubPathArrayOfValues)
}

type UpdateAccessPointRequest_CASPathSelectorFieldMask struct{}

func (UpdateAccessPointRequest_CASPathSelectorFieldMask) FieldPath() *UpdateAccessPointRequestCAS_FieldTerminalPath {
	return &UpdateAccessPointRequestCAS_FieldTerminalPath{selector: UpdateAccessPointRequestCAS_FieldPathSelectorFieldMask}
}

func (s UpdateAccessPointRequest_CASPathSelectorFieldMask) WithValue(value *access_point.AccessPoint_FieldMask) *UpdateAccessPointRequestCAS_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*UpdateAccessPointRequestCAS_FieldTerminalPathValue)
}

func (s UpdateAccessPointRequest_CASPathSelectorFieldMask) WithArrayOfValues(values []*access_point.AccessPoint_FieldMask) *UpdateAccessPointRequestCAS_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*UpdateAccessPointRequestCAS_FieldTerminalPathArrayOfValues)
}

type DeleteAccessPointRequestFieldPathBuilder struct{}

func NewDeleteAccessPointRequestFieldPathBuilder() DeleteAccessPointRequestFieldPathBuilder {
	return DeleteAccessPointRequestFieldPathBuilder{}
}
func (DeleteAccessPointRequestFieldPathBuilder) Name() DeleteAccessPointRequestPathSelectorName {
	return DeleteAccessPointRequestPathSelectorName{}
}

type DeleteAccessPointRequestPathSelectorName struct{}

func (DeleteAccessPointRequestPathSelectorName) FieldPath() *DeleteAccessPointRequest_FieldTerminalPath {
	return &DeleteAccessPointRequest_FieldTerminalPath{selector: DeleteAccessPointRequest_FieldPathSelectorName}
}

func (s DeleteAccessPointRequestPathSelectorName) WithValue(value *access_point.Reference) *DeleteAccessPointRequest_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*DeleteAccessPointRequest_FieldTerminalPathValue)
}

func (s DeleteAccessPointRequestPathSelectorName) WithArrayOfValues(values []*access_point.Reference) *DeleteAccessPointRequest_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*DeleteAccessPointRequest_FieldTerminalPathArrayOfValues)
}
